Seagate/cortx-manager

csm/cli/csm_client.py

<pre>
<code>
Story Ref (if any): EOS-13591
Not exiting even after login failure
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
cli continue even after login failure.
</code>
</pre>
<pre>
<code>
Handle parsing error, Handle CsmError in login
</code>
</pre>
<pre>
<code>
Locally Tested
(csmvenv) -bash-4.2$ python csm/cli/cortxcli.py
Username: admin
Password:
Server authentication check failed.
(csmvenv) -bash-4.2
</code>
</pre>

resolve EOS-13591 exit on login failure

---

csm/cli/schema/support_bundle.json

<pre>
<code>
Story Ref (if any): EOS-13631
Incorrect help for support_bundle generate command
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Incorrect help for support_bundle generate command
</code>
</pre>
<pre>
<code>
Corrected help string for suppot_bundle generate 
</code>
</pre>
<pre>
<code>
Locally Tested
</code>
</pre>

[main] Resolve EOS-13631 Corrected help string for support_bundle generate

---

csm/cli/schema/bundle_generate.json
csm/cli/support_bundle/bundle_generate.py
csm/cli/support_bundle/support_bundle.py
csm/core/blogic/const.py
csm/plugins/cortx/provisioner.py

<pre>
<code>
Story Ref (if any):EOS-12467
Update Support Bundle to Run without Root Access.
</code>
</pre>
<pre>
<code>
Partial Testing is Done Need to Check the Final Implementation once nowait option is openned.
</code>
</pre>
<pre>
<code>
Support Bundle Command only executes via root user however we need to be able to run the commands via non-root user as well.
</code>
</pre>
<pre>
<code>
Changing the SSH mechansm via Salt should remove the need for root user.
</code>
</pre>
<pre>
<code>
test/support_bundle.py
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
cortxcli support_bundle generate -h
usage: cortxcli …

EOS-12467 Changes for Support Bundle Cortx Branch

---

csm/cli/schema/alerts.json

<pre>
<code>
Story Ref (if any):EOS-13635
Default Value For Parameters needs to Be displayed in Alerts.
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Since Default Duration is 60sec There is a confusion between teams that alerts are not displayed.
</code>
</pre>
<pre>
<code>
Your Problem solution here...
</code>
</pre>
<pre>
<code>
Added Default Values in Help section
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
cortxcli$ alerts show -h
usage: cortxcli alerts show [-h] [-d DURATION [DURATION ...]]
[-l LIMIT [LIMIT ...]] [-s] [-a]
[-f …

EOS-13635 Changes for Help Section In Alerts

---

csm/core/agent/api.py

<pre>
https://jts.seagate.com/browse/EOS-13625
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
Check if session credentials object is not None when audit logging the session.
</pre>
<pre>
- login with IAM user credentials
</pre>

[CORTX1.0] EOS-13625: fix audit logging of session credentials

---

csm/cli/cortxcli.py

<pre>
<code>
Story Ref (if any): EOS-13727
CSM user with empty password is not working as expected.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Exception Is Thrown Since argparser  doesn't get cost import internally.
</code>
</pre>
<pre>
<code>
Fixed and Moved the String to Class rather than Const.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
cortxcli$ users create -h
usage: cortxcli users create [-h] username email {monitor,manage}
positional arguments:
username          Username for user used for Login.
email             User's valid email …

EOS-13727 -Cortx  Changes for Handling Import for Const in Argparse.

---

csm/core/agent/api.py

<pre>
https://jts.seagate.com/browse/EOS-13625
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
Check if session credentials object is not None when audit logging the session.
</pre>
<pre>
- login with IAM user credentials
</pre>

EOS-13625: fix audit logging of session credentials

---

csm/cli/cortxcli.py

<pre>
<code>
Story Ref (if any): EOS-13727
CSM user with empty password is not working as expected.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Exception Is Thrown Since argparser  doesn't get cost import internally.
</code>
</pre>
<pre>
<code>
Fixed and Moved the String to Class rather than Const.
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
cortxcli$ users create -h
usage: cortxcli users create [-h] username email {monitor,manage}
positional arguments:
username          Username for user used for Login.
email             User's valid email …

EOS-13727 Changes for Handling Import for Const in Argparse.

---

csm/cli/schema/system.json
csm/conf/setup.py
csm/core/blogic/const.py
csm/core/controllers/maintenance.py
csm/core/services/maintenance.py

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-13701
CSM GUI: Node names Under drop-downs on System maintenance page should display hostname /FQDN instead of srvnode1/2
</code>
</pre>
<pre>
<code>
Yes. UI-CLI-Backend Testing done on HW sm17-r18/sm18-r18
</code>
</pre>
<pre>
<code>
CSM GUI and Cortxcli showing nodeid (srvnode-1/srvnode-2) instead of actual Hostname of nodes
</code>
</pre>
<pre>
<code>
Hostname corresponding to nodeid are saved to conf at the csm_setup init. And same is utilized for showing status and triggering start/stop/shutdown node.
</code>
</pre>
<pre>
<code>
Status
</code>
</pre>
<pre>
<code>
After triggering Shutdown Node
</code>
</pre>
<pre>
<code>
After triggering Start Node
</code>
</pre>

[Cortx-dev]Eos 13701: Resolved-Node names shown instead of hostname in System maintainance dropdown

---

cicd/pyinstaller/requirment.txt
csm/core/controllers/usl.py
csm/core/data/models/usl.py
csm/core/services/usl.py
csm/core/services/usl_net_ifaces.py

This PR contains patches from two other PRs which were closed: https://github.com/Seagate/cortx-manager/pull/69 and https://github.com/Seagate/cortx-manager/pull/94 .
Besides that, it addresses one other issue: USL currently makes direct use of the S3 Account Server, which had its constructor updated recently, but USL was not updated for some reason. Now USL makes direct use of the respective CSM service app.
Description of https://github.com/Seagate/cortx-manager/pull/69 :
> # Problem Statement
> 
> [EOS-13391: Replace `GET /usl/v1/system/network/interfaces` stub in CSM/USL with correct implementation](https://jts.seagate.com/browse/EOS-13391)
> [EOS-13415: Implement: Replace `GET /usl/v1/system/network/interfaces` stub in CSM/USL with correct …

[CORTX1.0] EOS-13480: Validate CORTX v1.0 + UDS v1.0.2

---

csm/cli/schema/system.json
csm/conf/setup.py
csm/core/blogic/const.py
csm/core/controllers/maintenance.py
csm/core/services/maintenance.py

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-13701
CSM GUI: Node names Under drop-downs on System maintenance page should display hostname /FQDN instead of srvnode1/2
</code>
</pre>
<pre>
<code>
Yes. UI-CLI-Backend Testing done on HW sm17-r18/sm18-r18
</code>
</pre>
<pre>
<code>
CSM GUI and Cortxcli showing nodeid (srvnode-1/srvnode-2) instead of actual Hostname of nodes
</code>
</pre>
<pre>
<code>
Hostname corresponding to nodeid are saved to conf at the csm_setup init. And same is utilized for showing status and triggering start/stop/shutdown node.
</code>
</pre>
<pre>
<code>
Status
</code>
</pre>
<pre>
<code>
After triggering Shutdown Node
</code>
</pre>
<pre>
<code>
After triggering Start Node
</code>
</pre>

[MAIN]Eos 13701: Resolved-Node names shown instead of hostname in System maintainance dropdown

---

csm/core/controllers/users.py

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-13870
Wrong error message while trying to create existing user
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Wrong error message while trying to create existing user
</code>
</pre>
<pre>
<code>
Corrected message, changed Root to Admin
</code>
</pre>
<pre>
<code>
Tested locally with POSTMAN
Output
{
"message_id": "admin_already_exists",
"message_text": "Admin user already exists",
"extended_message": "Administrator"
}
</code>
</pre>

[CORTX] EOS-13870 Changed message root to Admin

---

csm/cli/command.py

<pre>
<code>
Story Ref (if any):https://jts.seagate.com/browse/EOS-13188
S3 bucket policy with invalid path is not working as expected.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Exception KeyError Is Thrown from common payload .
</code>
</pre>
<pre>
<code>
Handled KeyError Exception in fileparser of cli command
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
cortxcli$ s3bucketpolicy create mybucket 89 /root/invalid_path 45
usage: cortxcli.py s3bucketpolicy create [-h]
bucket_name Id Statement [Version]
Error: 2: file operation failed. please check if …

[CORTX] resolve EOS-13188 Handled KeyError in  fileparser of cli command

---

csm/plugins/cortx/health.py

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-13561
Handle SAS port alert and health view.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Earlier SAS alert comes only when all the 4 ports are down. 
Now, SSPL introduced a new sas:port alert which will come when each port is down. 
Also, earlier for SASHBA health view we were having 16 phy resource info. Now it has changed to only one resource. 
</code>
</pre>
<pre>
<code>
No changes required to handle new sas:port alert. 
Due to change in SASHBA health schema we handled it in our code. 
Currently for handling SAS health there was a special code written, with this change that special code is not needed and code is more generic now.
</code>
</pre>
<pre>
<code>
</code>
</pre>

[CORTX1.0-dev] EOS-13561-cortx-dev: Handled health view changes for SASHBA

---

csm/plugins/cortx/health.py

<pre>
<code>
Story Ref (if any): https://jts.seagate.com/browse/EOS-13561
Handle SAS port alert and health view.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Earlier SAS alert comes only when all the 4 ports are down. 
Now, SSPL introduced a new sas:port alert which will come when each port is down. 
Also, earlier for SASHBA health view we were having 16 phy resource info. Now it has changed to only one resource. 
</code>
</pre>
<pre>
<code>
No changes required to handle new sas:port alert. 
Due to change in SASHBA health schema we handled it in our code. 
Currently for handling SAS health there was a special code written, with this change that special code is not needed and code is more generic now.
</code>
</pre>
<pre>
<code>
</code>
</pre>

[Main] EOS-13561: Handled health view changes for SASHBA

---

csm/core/services/usl.py

[EOS-13480: Validate CORTX v1.0 + UDS v1.0.2](https://jts.seagate.com/browse/EOS-13480)
[EOS-13391: Replace `GET /usl/v1/system/network/interfaces` stub in CSM/USL with correct implementation](https://jts.seagate.com/browse/EOS-13391)
[EOS-14074: Revert use of cluster IP on `GET /usl/v1/system/network/interfaces`](https://jts.seagate.com/browse/EOS-14074)
See tickets for details.
No.
See tickets for details.
- Have `GET /usl/v1/system/network/interfaces` return management VIP instead of cluster IP
- `GET /usl/v1/system/network/interfaces` should return actual information on the management interface

[cortx1.0-dev] EOS-14074: Revert to use of cluster IP on `GET /usl/v1/system/network/interfaces`

---

csm/cli/scripts/system.py
csm/common/process.py
csm/core/services/storage_capacity.py

<pre>
<code>
Story Ref (if any):EOS-13563
System Startup displays error message even when hctl command returns success.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
System Startup displays error message even when hctl command returns success.
</code>
</pre>
<pre>
<code>
Since Hctl writes multiple lines some values are captured as error. this results in errors . Replaced error check from messgaes to rc.
</code>
</pre>
<pre>
<code>
Locally Tested
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
usage: cortxcli system [-h] {startup} ...
positional arguments:
{startup}
startup   Brings back the system after …

EOS-13563 Fixing error when startup command is being executed.

---

csm/core/controllers/usl.py
csm/core/services/s3/buckets.py
csm/core/services/usl.py

<pre>
Story Ref (if any):EOS-14045
</pre>
<pre>
</pre>
<pre>
If registration failed user is not informed with exact reason why it failed.
</pre>
<pre>
Replace 'Device registration failed' message with 'Lyve Pilot failed to register the device'
</pre>
<pre>
On UDS side failure the updated message is displayed on the popup.
</pre>

[CORTX1.0] EOS-14045: amend Lyve Pilot registartion failure message

---

csm/conf/etc/csm/csm.conf
csm/core/agent/api.py
csm/core/agent/csm_agent.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14059
Additional logs are generated for each REST call.
USL is polling on some api's , added configuration to disable audit logs for usl api's except '/usl/v1/registerDevice'
</pre>
<pre>
NO
</pre>
<pre>
Acccess log for aiohttp is adding log for each REST call apart from audit log.
</pre>
<pre>
Disabling aiohttp access log.
</pre>
<pre>
Tested on vm access logs are not log in csm_agent.log 
</pre>

[CORTX] EOS--14059 Disabled access log for aiohttp as audit log is logging most of details

---

csm/core/blogic/const.py
csm/core/services/health.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14145
In case of health view we show UI with old hostname
</pre>
<pre>
Yes
</pre>
<pre>
In case of manufacturing, hostname will be different from field. Health map gets generated at time of Manufacturing which embed hostname in json file itself. This will end up showing old hostname, when hostname get changed on filed.
</pre>
<pre>
Short term solution:--
instead of hostname use node salt id(srvnode-1, srvnode-2) instead of hostname.
CSM will map hostname to salt id and do a hack to extract srvnode details from keys.
</pre>
<pre>
</pre>

[CORTX-DEV] EOS-14145-cortx-dev: Health view changes for hostname

---

csm/core/blogic/const.py
csm/core/services/health.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14145
In case of health view we show UI with old hostname
</pre>
<pre>
Yes
</pre>
<pre>
In case of manufacturing, hostname will be different from field. Health map gets generated at time of Manufacturing which embed hostname in json file itself. This will end up showing old hostname, when hostname get changed on filed.
</pre>
<pre>
Short term solution:--
instead of hostname use node salt id(srvnode-1, srvnode-2) instead of hostname.
CSM will map hostname to salt id and do a hack to extract srvnode details from keys.
</pre>
<pre>
</pre>

[MAIN] EOS-14145: Health view changes for hostname

---

csm/conf/etc/cron.hourly/csm_logrotate
csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14247
</pre>
<pre>
Yes
</pre>
<pre>
Privisioner has made change to invoke logrotate hourly just by adding conf file to /etc/logrotate_hourly.d/
</pre>
<pre>
Updated csm logrotate to use provisioner changes
</pre>
<pre>
Logrotate triggered for csm_agent.log for more than 10mb size
</pre>
Signed-off-by:

[CORTX-DEV] Eos 14247 Improve logrotate code for CSM logs based on changes done by provisioner

---

csm/core/services/health.py

<pre>
Story Ref (if any):EOS-14334: System shut-down from CSM not working.
</pre>
<pre>
Yes/No
</pre>
<pre>
System shutdown is not working.
</pre>
<pre>
This issue regressed due to a change in health map logic. Fixed it.
</pre>
<pre>
</pre>
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>

[cortx1.0-dev]EOS-14334: System shut-down from CSM not working.

---

csm/core/blogic/const.py

<pre>
Story Ref (if any):Move csm logrotate conf to logrotate.d instead of logrotate_hourly.d
</pre>
<pre>
Yes
</pre>
<pre>
/etc/logrotate_hourly.d/ folder is removed by provisioner.
</pre>
<pre>
Moving csm logrotate conf file to /etc/logrotate.d
</pre>
<pre>
Checked file after csm_setup init. csm logrortate file gets created in /etc/logrotate.d/ folder
</pre>
Signed-off-by:

[Cortx-dev] Move csm logrotate conf to logrotate.d instead of logrotate_hourly.d

---

csm/cli/support_bundle/csm_bundle_generate.py
csm/conf/etc/csm/csm.conf

<pre>
<code>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14242
Added additional files for elasticsearch support_bundle
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Add support bundle for uds and elasticsearch.
</code>
</pre>
<pre>
<code>
Add support bundle for uds and elasticsearch.
</code>
</pre>
<pre>
<code>
Unit Testing details here...
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
usage: cortxcli support_bundle generate [-h] [--os]
[-c {all,csm,sspl,s3server,core,hare,provisioner,os,health_map,manifest,uds,elasticsearch} [{all,csm,sspl,s3server,core,hare,provisioner,os,health_map,manifest,u …

[Cortx-dev] EOS-14242 added additional elasticsearch log file for support_bundle

---

csm/cli/support_bundle/csm_bundle_generate.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14531
</pre>
<pre>
No
</pre>
<pre>
tar file was created outside uds/elastisearch folder
</pre>
<pre>
created tar file inside corresponding component folder 
</pre>
<pre>
</pre>
Signed-off-by:

[CORTX-dev] EOS-14531 moved bundle file for csm, uds, elasticsearch inside corressponding folder

---

csm/cli/schema/bundle_generate.json
csm/cli/schema/support_bundle.json
schema/commands.yaml

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
Ref: https://github.com/Seagate/cortx-manager/pull/201 csm
Ref: https://github.com/Seagate/cortx-ha/pull/202 ha
<pre>
https://jts.seagate.com/browse/EOS-14006
</pre>
<pre>
Yes
</pre>
<pre>
Support bundle for ha is missing
</pre>
<pre>
Add ha support bundle in cortxcli
</pre>
<pre>
Integration testing is done
No unit testing available.
</pre>

Add support bundle for ha

---

csm/core/blogic/const.py
csm/plugins/cortx/provisioner.py

<pre>
Story Ref (if any): EOS-14372
</pre>
<pre>
Yes
</pre>
<pre>
Bucket list failing to return list for 500 bucket account
</pre>
<pre>
Stored network configuration fetched from provisioner in in-memory. So while creating s3_url, it will get the cluster IP from in-memory instead of fetching it from provisioner evry time. 
</pre>
<pre>
</pre>

EOS-14372: Bucket list failing to return list for 500 bucket account

---

cicd/build.sh
csm/cli/schema/bundle_generate.json
csm/cli/schema/csm_bundle_generate.json
csm/cli/schema/support_bundle.json
csm/cli/support_bundle/csm_bundle_generate.py
csm/conf/alerts_setup.yaml
csm/conf/etc/csm/csm.conf
csm/core/services/alerts.py
schema/commands.yaml

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14243
Add FRU Alerts as part of support bundle
</pre>
<pre>
Yes
</pre>
<pre>
Requirement was to add fru alerts to support bundle.
</pre>
<pre>
Added fru alerts to support bundle
</pre>
<pre>
[root@ssc-vm-c-1058 722996]# cortxcli support_bundle generate -h
usage: cortxcli support_bundle generate [-h] [--os]
[-c {all,csm,sspl,s3server,core,hare,provisioner,os,health_map,manifest,alerts} [{all,csm,sspl,s3server,core,hare,provisioner,os,health_map,manifest,alerts} ...]]
comment
positional arguments:
comment               Specify the Reason for Generating Support Bundle.
optional arguments:
-h, --help            show this help message and exit
--os                  Generate Only OS Logs
-c …

[CORTX-DEV] EOS-14243-cortx-dev: Adding fru alerts to support bundle

---

csm/common/comm.py
csm/conf/etc/csm/csm.conf
csm/core/blogic/const.py
csm/core/services/alerts.py
csm/plugins/cortx/alert.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14335
Private data network port down on a node where CSM is running is not seen by CSM
</pre>
<pre>
Yes
</pre>
<pre>
When Pvt nw is down elasticsearch also went down. So, when CSM receives the alert due to elasticsearch is still in cloning process CSM is not able to save the alert in db. Also, CSM ack that alert and it omits from RMQ. 
</pre>
<pre>
Elasticsearch cloning requires few seconds so we will try to first connect to elasticsearch and then start the process of saving the alerts. Also, in case of any exception we will not ack the alert so that it remains in RMQ.
</pre>
<pre>
</pre>

[CORTX-DEV] EOS-14335-cortx-dev: Alerts not visible for Pvt data nw

---

csm/conf/etc/csm/csm.conf
csm/core/blogic/const.py
csm/core/services/alerts.py
csm/plugins/cortx/alert.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14335
Private data network port down on a node where CSM is running is not seen by CSM
</pre>
<pre>
Yes
</pre>
<pre>
When Pvt nw is down elasticsearch also went down. So, when CSM receives the alert due to elasticsearch is still in cloning process CSM is not able to save the alert in db. Also, CSM ack that alert and it omits from RMQ. 
</pre>
<pre>
Elasticsearch cloning requires few seconds so we will try to first connect to elasticsearch and then start the process of saving the alerts. Also, in case of any exception we will not ack the alert so that it remains in RMQ.
</pre>
<pre>
</pre>

[MAIN] EOS-14335: Alerts not visible for Pvt data nw

---

cicd/build.sh

<pre>
</pre>
<pre>
No
</pre>
<pre>
Build is failing for LDR build.
</pre>
<pre>
Updated CSM_PATH to BASE_DIR
</pre>
<pre>
NA
</pre>

Build is failing due to CSM PATH is not available

---

cicd/pyinstaller/requirment.txt
csm/core/blogic/const.py
csm/core/services/security.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14633
local timezone not printed in date
</pre>
<pre>
No
</pre>
<pre>
Local timezone of server is not in date  
</pre>
<pre>
Added local timezone in date format
</pre>
<pre>
Tested code snippet independently 
Output date format is 
2020-10-27 04:14:48 UTC+0000
2020-10-27 09:44:48 IST+0530
</pre>
Signed-off-by:

[Main] EOS-14633 Added local timezone to date format

---

cicd/pyinstaller/requirment.txt
csm/core/blogic/const.py
csm/core/services/security.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14633
local timezone not printed in date
</pre>
<pre>
No
</pre>
<pre>
Local timezone of server is not in date  
</pre>
<pre>
Added local timezone in date format
</pre>
<pre>
Tested code snippet independently 
Output date format is 
2020-10-27 04:14:48 UTC
2020-10-27 09:44:48 IST
</pre>
Signed-off-by:

[Cortx-dev] Eos 14633 SSL certificate alert displays incorrect time zone

---

csm/cli/schema/s3accounts.json
csm/core/services/s3/accounts.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14746
</pre>
<pre>
No
</pre>
<pre>
Need additional fields from s3 account creations
</pre>
<pre>
Returned requested fields
</pre>
<pre>
cortxcli$ s3accounts create s3_acc_cli s3_cli@test.com
Password must contain the following.
1) 1 upper and lower case character.
2) 1 numeric character.
3) 1 of the !@#$%^&*()_+-=[]{}|' characters.
Password:
Confirm Password:
Are you sure you want to perform "s3accounts create" command? [Y/n] y
+--------------+-----------------+--------------+------------------------------------------------------------------+------------------------+------------------------------------------+
| Account Name |  Account Email  |  Account Id  | …

[Crtx-dev] EOS-14746 returned account_id and canonical_id on s3account create

---

csm/core/services/security.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14633
Corrected one call for async by await
</pre>
<pre>
No
</pre>
<pre>
Local timezone of server is not in date  
</pre>
<pre>
Added local timezone in date format
</pre>
<pre>
Tested code snippet independently 
Output date format is 
2020-10-27 04:14:48 UTC
2020-10-27 09:44:48 IST
</pre>
Signed-off-by:

[Main] EOS-14633 Added await for async call

---

csm/common/ha_framework.py
csm/conf/etc/csm/csm.conf

<pre>
Story Ref (if any):EOS-14583
Shutdown not working using GUI or CLI.
</pre>
<pre>
Yes
</pre>
<pre>
System is not getting shutdown either from GUI nor from CLI. Since the cronjobs is not executing the command.
</pre>
<pre>
Updated the Cron Time to 2 minutes to check the cron issues
</pre>
<pre>
None
</pre>
Signed-off-by: <prathamesh.rodi@seagate.com>

EOS-14583 Changing Cron Time to 120 seconds to remove cron time.

---

csm/conf/setup.py
csm/core/blogic/const.py

<pre>
</pre>
EOS-14978
<pre>
No
</pre>
<pre>
rabbitmq-server cluster_status command output has been changed between 3.7 and 3.8.9-1.
</pre>
<pre>
Adopt parsing code accordingly. 
</pre>
<pre>
No
</pre>
Signed-off-by:

[Cortx 1.0] EOS-14978

---

csm/cli/schema/bundle_generate.json
csm/cli/schema/support_bundle.json
schema/commands.yaml

<pre>
<code>
Story Ref (if any): EOS-15306
Motr logs not present in support bundle
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Motr Logs are not present in Support Bundle.
</code>
</pre>
<pre>
<code>
Motr setup.yaml files path was updated and hence the file path is updated now.
</code>
</pre>
<pre>
<code>
Unit Testing details here...
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Update Cli Command Help Section....
</code>
</pre>
<pre>
<code>
Update Cli Expected Output Here.... 
</code>
</pre>

EOS-15306 Support Bundle Fix for Motr Path change

---

csm/cli/support_bundle/bundle_generate.py

<pre>
<code>
Story Ref (if any):EOS-15184
Support bundle generation failed for provisioner and health_map
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Logs for Error were displayed under Debug.
</code>
</pre>
<pre>
<code>
Added a Log Error Line to Print Log when logger is in INFO Level.
</code>
</pre>
<pre>
<code>
Local Testing Done
</code>
</pre>
<pre>
<code>
NA
</code>
</pre>
<pre>
<code>
NA
</code>
</pre>
<pre>
<code>
NA
</code>
</pre>

EOS-15184 Fxing Log Level in Error Messages for Support Bundle.

---

cicd/auxiliary/etc/database.json
cicd/build.sh
csm/cli/conf/etc/cli/database_cli.yaml
csm/conf/etc/csm/database.yaml

Reverts Seagate/cortx-manager#293
Reverting these code changes as the changes in generic db needs to be done with HA, CSM and CSM and also needs to be handled in there respective code usage. This causing build failures.

Revert "EOS-15055 Multiple hosts"

---

csm/cli/schema/csm_setup.json
csm/common/conf.py
csm/common/payload.py
csm/conf/setup.py
csm/conf/uds.py
csm/core/services/usl.py

[EOS-14470: Configure UDS/HAproxy config from `csm_setup`](https://jts.seagate.com/browse/EOS-14470)
[EOS-15653: Re-enable UDS/HAproxy config](https://jts.seagate.com/browse/EOS-15653)
Yes.
- Revert changes which disabled UDS data movement over data network
- Add new HAproxy frontend entry on management VIP for UDS
* Loosen restrictions on the number of minions during HAproxy config step; it required two minions, which didn't work on VM setups
- Provide a configuration option, namely `UDS.public_ip`, which allows USL to override its dependency on cluster IP to derive network interface details for `GET /usl/v1/system/network/interfaces`.
[_Edit Dec/21/2020_]
- Add new option to `csm_setup config`, `--uds-public-ip`, to allow for …

EOS-15653: Re-enable UDS/HAproxy config

---

csm/conf/uds.py

[EOS-14470: Configure UDS/HAproxy config from `csm_setup`](https://jts.seagate.com/browse/EOS-14470)
[EOS-16166: HAproxy config on inactive node fails because management IP is not assigned to it](https://jts.seagate.com/browse/EOS-16166)
See tickets for details.
Yes.
See tickets for details.
Add `transparent` option to HA proxy `bind` config for the management VIP.
Should be tested in conjunction with EOS-14470 ([see PR](https://github.com/Seagate/cortx-manager/pull/330)). Additionally to its test cases, we must ensure that HAproxy configuration on both nodes is successful and its respective services run with no issues.

[cortx-1.0] EOS-16166: HAproxy config on inactive node fails because management IP is not assigned to it

---

csm/conf/salt.py
csm/conf/setup.py

<pre>
Story Ref (if any):CSM: UDX: LR Device registration failed on 565
</pre>
<pre>
Yes
</pre>
<pre>
After user deletion in post_update, permissions for udx and csm folders are not updated. Deu to this device registration fails. 
</pre>
<pre>
Removed user deletion logic and password obtained from provisioner is updated to user
</pre>
<pre>
</pre>
Signed-off-by: Udayan Yaragattikaar<udayan.yaragattikar@seagate.com>

Eos:16689-Removed user deletion logic from csm_setup post_update

---

csm/conf/configure.py
csm/conf/setup.py

<pre>
Story Ref (if any): EOS-16153
CSM Mini Provisioner 
</pre>
<pre>
Yes
</pre>
<pre>
CSM Setup Configure Failed due to incorrect  vm state  setting.
</pre>
<pre>
Fixed If Statement in the Code as well as Machine-ID removed \n
</pre>
<pre>
Tested Manually.
</pre>

EOS-16153 Fix for Machine ID Code Conversion.

---

csm/conf/setup.yaml

<pre>
Story Ref (if any): EOS-17010
CSM Mini-Provisioner Integration with Provisioner.
</pre>
<pre>
Yes
</pre>
<pre>
Need to Integrate CSM Mini Provisoner with Provisioner API to be able to Deploy on Single Node VM Instance.
</pre>
<pre>
Changes made in setup.yaml that is called by Provisioner to Implement while Intallation.
</pre>
<pre>
This will be tested with provisioner while Setup.
</pre>
Signed-off-by:

EOS-17010 Updating setup.yaml for CSM Mini Provisioner Integration

---

csm/core/services/security.py

Modified SSL certificate expiry IEM message
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-17586
</pre>
<pre>
No
</pre>
<pre>
More informative message is required for SSL certificate expiry message.
</pre>
<pre>
Added the more informative message for SSL certificate expiry message
</pre>
<pre>
</pre>
Signed-off-by: pawan.kumarsrivastva@seagate.com

EOS-17586: Modified SSL certificate expiry IEM message

---

cicd/cortxcli.spec
cicd/csm_agent.spec

<pre>
Story Ref (if any): NA
</pre>
<pre>
Yes
</pre>
<pre>
Incorrect License information observed for csm-agent rpm and cortxcli rpm 
</pre>
<pre>
Updated correct License information  for csm-agent rpm and cortxcli rpm 
</pre>
<pre>
[root@ssc-vm-2292 731368]# rpm  -qa --qf "%{name} : %{license}\n" | grep cortx-csm_agent
cortx-csm_agent : Seagate
</pre>
<pre>
[root@ssc-vm-2292 731368]# rpm  -qa --qf "%{name} : %{license}\n" | grep cortx-cli
cortx-cli : Seagate
</pre>
Signed-off-by: Udayan Yaragattikar (udayan.yaragattikar@seagate.com)

Update CSM RPM License Information

---

csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/routes.py
csm/core/controllers/s3/server_info.py
csm/core/services/s3/accounts.py
csm/core/services/s3/buckets.py
csm/core/services/s3/iam_users.py
csm/core/services/s3/server_info.py

Story Ref (if any): [EOS-17506](https://jts.seagate.com/browse/EOS-17506)
Yes
When the cluster ID is not configured on the system the vast number of S3 REST endpoints stops working.   
Failures happen because services apart from accessing the S3 server, try to solicit the cluster ID from the provisioner (not configured) in order to build S3 server's URL and hence the whole request fails.
The solution is to clear S3 services from all the provisioner calls so that S3 REST is responsible for sole resource (S3 server). In order to build S3 server's URL the separate REST endpoint is allocated: GET /api/v1/s3, that could be considered as the description of the system's S3 server.
Try the affected APIs either from CLI or UI
- create S3 account,
- list S3 accounts,
- create IAM user,
- list IAM …

EOS-17506: S3 use cases should be working on VM through CSM (BE)

---

cicd/pyinstaller/requirment.txt
csm/core/services/file_transfer.py
csm/core/services/firmware_update.py
csm/core/services/hotfix_update.py

<pre>
Story Ref (if any): EOS-18376-Build #589: SMS2: Upload of ISO is failing during update if /tmp/hotfix folder is missing on the node1
</pre>
<pre>
Yes
</pre>
<pre>
File upload fails, due to storage directory /tmp/hotfix was missing, 
</pre>
<pre>
Added logic to to software update as well as firmware functionality, to check weather storage directories are present or not. If absent then create.
</pre>
<pre>
Following scenarios tested
1. Upload of package when storage directory is present when csm_agent starts at very first time. --> Happy Path
2. Upload of package when storage directory is present at the time when csm_agent restarts
3. Upload of package when /tmp/fw_update and /tmp/hotfix directories are not present. At this time storage directories are created even if they are not …

[MAIN]EOS-18376:  Check if storage directories are present for file upload, else create

---

csm/conf/configure.py
csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-18499 
</pre>
<pre>
Yes
</pre>
<pre>
Preboarding Admin user creation failing on R2 VM, due to password decryption issue.
</pre>
<pre>
Password decryption issue resolved. This was deu to the change in key which is used in encryption logic. 
Also there is a change from provisioner side as well. For that seperate PR raised by mazhar from provisioner side.
</pre>
<pre>
</pre>
Signed-off-by:

Admin creation issue resolution on R2 VM

---

cicd/build.sh
cicd/cortxcli.spec
cicd/pyinstaller/product_cli.spec
csm/cli/conf/cli_setup.py
csm/cli/conf/configure.py
csm/cli/conf/init.py
csm/cli/conf/post_install.py
csm/cli/conf/reset.py
csm/cli/conf/test.py
csm/cli/schema/cli_setup.json
csm/core/blogic/const.py

Story Ref (if any): [EOS-18381](https://jts.seagate.com/browse/EOS-18381)
Yes
The cli_setup utility is required to update the CORTX CLI configuration according to the Mini-provisioner API specification.
Implemented the cli_setup utility based on the csm_setup framework.
- cli_setup config --config \<URL\>
Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>

EOS-18381: Restricted CLI: CLI Setup command to update configuration

---

csm/core/blogic/models/audit_log.py
csm/core/services/audit_log.py

<pre>
S3 audit logs are throwing exception.
Story Ref (if any): https://jts.seagate.com/browse/EOS-18555 
</pre>
<pre>
Yes
</pre>
<pre>
S3 audit logs were not shown in case of entries with msg field. 
</pre>
<pre>
"msg" field is added in S3AuditLogModel in CSM.
</pre>
<pre>
Tested on smc69-m10.colo.seagate.com and smc70-m10.colo.seagate.com for the timestamp when there are entries with msg field
</pre>
Signed-off-by:

S3 Audit log fix for msg field

---

csm/core/controllers/usl.py

UDX SaaS endpoint changed in cortx manager
<pre>
</pre>
[EOS-18875](https://jts.seagate.com/browse/EOS-18875)
<pre>
No
</pre>
<pre>
Refer to the ticket.
</pre>
<pre>
UDX SaaS endpoint changed in cortx manager to /usl/version/udx_saas format
</pre>
<pre>
CSM Login:
- Login to CSM UI
- click on lyve-pilot link
- Logged in to S3 account
- selected/created bucket
- Created I am user
- Able to see URL field on csm gui (which is response of udx_saas API)
</pre>

UDX SaaS endpoint changed in cortx manager

---

cicd/pyinstaller/requirment.txt
csm/core/blogic/const.py
csm/core/services/s3/buckets.py
csm/core/services/usl.py
csm/plugins/cortx/s3.py
test/s3/test_s3.py
test/test_data/args.yaml

Story Ref (if any): [EOS-18569](https://jts.seagate.com/browse/EOS-18569)
Yes
At the beginning of CORTX CSM team chose boto2 for handling CORTX-specific requests to IAM server (e.g. CreateAccount, CreateAccountLoginProfile, etc.). Per architects' query the dependency on boto2 should be removed.
- Implement a method for sending arbitrary AWS-signed requests leveraging boto3's SignV4.
- Implement a new parser for IAM server's responses (the old one leveraged boto.XMLParser).
- csm/test/plans/s3.pln:test_s3

EOS-18569: BE: Use boto3 package instead of boto package

---

csm/core/blogic/const.py
csm/core/services/alerts.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19002
Add hostname to alert response.
</pre>
<pre>
Yes
</pre>
<pre>
Currently node id is shown on UI. Hostname should be shown on UI instead of node id. So hostname should be added in the response.
</pre>
<pre>
CSM maintains mapping between host id and host name. The alert received from SSPL has host id. CSM will check the mapping and add hostname from the mapping. If mapping is not available, the host id will be returned.
</pre>
<pre>
Tested on UI
</pre>
Signed-off-by:

Add hostname in Alerts response

---

csm/common/service_urls.py
csm/core/controllers/s3/server_info.py
csm/core/services/s3/server_info.py

<pre>
</pre>
[EOS-18876](https://jts.seagate.com/browse/EOS-18876)
<pre>
Yes
</pre>
<pre>
On backend, there is a dedicated endpoint ({{GET /api/v1/s3) }}to get s3 URLs. 
But it is not returning the s3 url in the required format s3://ip-address:port. 
</pre>
<pre>
Added query parameter support for getting s3_urls from backend for supported schemas - http,https,s3
After merge of this PR, csm_web code should be modified and consume the GET api -
/api/{version}/s3?schemas=s3 to get the s3_url and add it to the payload of Lyve Pilot registration api.
</pre>
<pre>
</pre>
Signed-off-by:

EOS-18876: Added query parameter support for getting s3_urls from backend for supported schemas - http,https,s3

---

csm/common/comm.py
csm/core/agent/csm_agent.py
csm/plugins/cortx/alert.py
csm/plugins/cortx/health.py
test/message_bus/test_consumer.py
test/message_bus/test_producer.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19062
</pre>
<pre>
Yes
</pre>
<pre>
To ease use of Message Bus, we have made MessageBus class as singleton (not yet part of main branch).
This implies that, one can go ahead without instantiating MessageBus class, or instantiate once or multiple time. All will work. 
The recommended way is not to instantiate MessageBus class.
This brings certain changes in the client classes. Here is the summary of all such changes:
----------------------
MessageBus class is made singleton and it is not necessary to pass MessageBus instance as a parameter to any of the clients i.e., Producer, Consumer or Admin.(It can be included at the end if needed) 
All client …

EOS-19062: Incorporated the changes wrt Singleton MessageBus class

---

csm/conf/setup.py
csm/conf/uds.py

[EOS-18886: Create & Build OVA 1.0.4](https://jts.seagate.com/browse/EOS-18886)
Yes.
See tickets for details.
- Add following checks before running UDS config step:
* ~`csm_setup` is running on VM;~ _(note: removed after review)_
* `lyve_pilot` is not on the list of unsupported features for the machine storage type.
- Do not raise an exception when attempting to remove UDS config directory if it does not exist
N/A

EOS-18886: Execute UDS config only in supported devices 

---

csm/core/agent/api.py
csm/core/blogic/models/audit_log.py
csm/plugins/cortx/s3.py

<pre>
Story Ref (if any): msg rough field error is coming.
</pre>
<pre>
Yes
</pre>
<pre>
The are some old logs which are not inserted in required json format. which leads to the error and does not display the audit logs.
</pre>
<pre>
1. msg field is added in CSMAuditLog Model
2. added default values for all the fields
</pre>
<pre>
1. Tested by doing S3 operations from UI as well as CLI
2. Tested with Alerts, stats from UI
3. Tested view logs for seven days
4. Tested with downloading audit logs for seven days.
</pre>

Audit log fix for msg field

---

csm/plugins/cortx/provisioner.py
schema/commands.yaml

<pre>
</pre>
[EOS-19159](https://jts.seagate.com/browse/EOS-19159)
<pre>
Yes
</pre>
<pre>
1. Nowait agrument for bundle_generation in provisioner plugin was throwing invalid argument error.
2. setup-ha.yaml has been moved to cortx-ha but setup-ha.yaml file path is still present under hare key in 
commands.yaml
</pre>
<pre>
1. As nowait argument error has been fixed from provisioner side, added it back to provisioner plugin in CSM code.
</pre>
[JIRA Ticket ref for provisioner's fix](https://jts.seagate.com/browse/EOS-19561)
<pre>
2. Removed erroneous path of setup-ha.yaml which was nested under hare key in commands.yaml
</pre>
[Ref. for setup-ha.yaml removal](https://jts.seagate.com/browse/EOS-19522?focusedCommentId=2088678&page=com.atlassian.jira.plugin.system.issuetabp …

EOS:19159 Changes for support_bundle to sync up with other components

---

csm/core/services/audit_log.py

<pre>
</pre>
[EOS-19475](https://jts.seagate.com/browse/EOS-19475)
<pre>
No
</pre>
<pre>
1. offset value was considered as records to be skipped from the entire result set,
instead offset value should have been calculated as per the pageNumber selected on GUI.
Due to this repeated records was getting displayed in the csm audit logs table pages on GUI.
</pre>
<pre>
2. Applied formula for offset calculation according to PageNumber selected on GUI.
</pre>
<pre>
Tested on UI.
</pre>

EOS-19475: Pagination logic corrected for CSM Audit Logs

---

csm/conf/configure.py
csm/conf/post_install.py

<pre>
</pre>
<pre>
No
</pre>
<pre>
</pre>
<pre>
As per the latest discussion over rsyslog configuration,  decision is made that rsyslog configuration for csm will be moved in post-install
</pre>
<pre>
</pre>
Signed-off-by:

Moving ryslog config to post install

---

csm/common/timeseries.py
csm/core/services/stats.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14872, https://jts.seagate.com/browse/EOS-14907
</pre>
<pre>
Yes
</pre>
<pre>
EOS-14872: GET API for system stats returns 500 for one missing TO and FROM params
EOS-14907: GET API /api/v1/stats returns 500 for invalid values for METRIC and TOTAL_SAMPLE parameter
</pre>
<pre>
Raise InvalidRequest exceptions instead CsmInternalError exceptions because parameters are  not valid.
</pre>
<pre>
Yes
</pre>
Signed-off-by: SrikantVishwakarma <srikant.vishwakarma@seagate.com>

EOS-14872 and EOS-14907 Invalid response code in exceptions

---

csm/core/services/appliance_info.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19465
</pre>
<pre>
Yes
</pre>
<pre>
EOS-19658 : Create API which returns cluster ID
</pre>
<pre>
Updated appliance_info api to return cluster ID as well.
</pre>
<pre>
Yes
</pre>
Signed-off-by:  SrikantVishwakarma <srikant.vishwakarma@seagate.com>

EOS-19658: Create API which returns cluster ID

---

csm/conf/post_install.py
experiments/pam/pam_cortx.c
experiments/pam/readme.md

* Correction in csm_agent login url and other minor changes
* Curl option for failed API response has set to TRUE
* PAM readme.updated
* Password prompt issue resolved
* PAM module renamed to pam_cortx
* PAM readme updated
* Removed unnecessary comments
* Trying to fix codacy issue
Co-authored-by: kupranay …

Tmain to main branch closure

---

csm/common/errors.py

Signed-off-by: root <root@ssc-vm-2608.colo.seagate.com>
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-20752
</pre>
<pre>
No
</pre>
<pre>
BaseError class was renamed in py-utils and because of this 1 node deployment is failing.
</pre>
<pre>
Renamed the class to appropriate one 
</pre>
<pre>
</pre>
Signed-off-by:

EOS-20752: Renaming BaseError class name to UtilsError

---

csm/core/controllers/audit_log.py
csm/core/services/audit_log.py

[EOS-20670: Create new endpoint that returns audit logs schema](https://jts.seagate.com/browse/EOS-20670)
No
- Implement new endpoint `GET /api/v2/auditlogs/schema_info`, accessible to users with LIST permissions for the Audit Log feature.
None.
- Endpoint `GET /api/v2/auditlogs/schema_info` should return status code 200 with the following payload:
```
[
{
"field_id": "timestamp",
"label": "Timestamp",
"display_id": 201,
"display": true,
"sortable": true,
"filterable": false
},
{
"field_id": "user",
"label": "User",
"display_id": 301,
"display": true,
"sortable": true,
"filterable": false
},
{
"field_id": "remote_ip",
"label": "Remote IP",
"display_id": 401,
"display": false,
"sortable": true,
"filterable": false
},
{
"field_id": …
```

EOS-20670: Create new endpoint that returns audit logs schema

---

csm/core/controllers/s3/iam_users.py
csm/core/controllers/validators.py

[EOS-20545](https://jts.seagate.com/browse/EOS-20545)
While creating IAM users using cortxcli, if validation fails for username or password value, generic error message is getting displayed on console - "error(400): Error:- Invalid request message received."
This error message does not indicate which parameter is invalid and creates confusion.
"error(400): Error:- Invalid request message received."
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Y
This patch will display appropriate error message if user enters invalid combinations of username & password while creating IAM users using cortxcli.
- _For Bug describe the fix here._ 
Error description updated in code …

EOS-20545: Showing appropriate error message if invalid Username and Password combinations entered while creating IAM users from cortxcli

---

csm/core/agent/api.py
csm/core/blogic/const.py

The current implementation queries Elasticsearch at each and every API call to check if the endpoint at hand is supported or not.  This PR queries Elasticsearch only once for details on unsupported features and checks these details instead.
The idea behind this change is to avoid CSM failures related to Elasticsearch timeouts, as described in [EOS-20811](https://jts.seagate.com/browse/EOS-20811).  Please check the ticket for further details.
- Create new private class variable in `CsmRestApi` to store unsupported features details;
- Iterate over these details at every API call instead of querying Elasticsearch.
- _Confirm that Test Cases are added (for both the cases, …

EOS-20811: Keep unsupported features info in `CsmRestApi`

---

csm/core/services/audit_log.py

- [EOS-21280](https://jts.seagate.com/browse/EOS-21280)
- Add data type description to the "Timestamp" header of CSM audit logs.
- The amendment is self-descriptive.
-  _Check if the description is clear and explained._ 
-  _Check Acceptance Criterion is defined._
-  _All the tests performed should …

EOS-21280: add data type for timestamp in CSM audit log headers

---

csm/core/controllers/users.py
csm/core/services/users.py

- [EOS-22065](https://jts.seagate.com/browse/EOS-22065): search and filter for csm users not working as expected.
- Per Pranay's request changing the Users role filter operation from 'eq' to 'like'.
- Remove the check for the valid User role passed as a role filter.
-  _Check if the description is …

EOS-22065: change the Users role filter from 'eq' to 'like'

---

csm/core/services/audit_log.py

- [EOS-21280](https://jts.seagate.com/browse/EOS-21280): CSM: audit logs Sorting and filtering enabled.
- Per Pranay's request make only 'timestamp' and 'response_code' fields sortable.
-  _Check if the description is clear and explained._ 
-  _Check Acceptance Criterion is defined._
-  _All the …

EOS-21280: BE: update sortable fields of CSM audit logs schema

---

csm/core/services/users.py

https://jts.seagate.com/browse/EOS-22643
There will be no first admin creation workflow in CSM agent. as admin will be created during csm_setup config phase
- …

EOS-22643: F-11D: Remove admin user creation workflow during preboarding

---

cicd/cortxcli.spec
csm/conf/post_upgrade.py

https://jts.seagate.com/browse/EOS-23138
Csm_web not running on managment ip after sw upgrade is performed
Removed replacing .env file in postupgrade. 
- _Coding conventions are followed and code is consistent. Yes/No?_y
- _Confirm All CODACY errors are resolved. Yes/No?_y
```
021-07-28 07:51:33,019 - INFO - Fire pre-upgrade event (node level)
2021-07-28 07:51:39,966 - INFO - Upgrading sw: '['utils', 'motr', 's3', 'hare', 'ha', 'sspl', 'uds', 'csm']'
2021-07-28 07:51:39,967 - INFO - Upgrading/Installing 'utils' on '['srvnode-1']'
2021-07-28 07:52:09,257 - INFO - Upgrading/Installing 'motr' on '['srvnode-1']'
2021-07-28 07:52:52,000 - INFO - Upgrading/Installing 's3' on '['srvnode-1']'
2021-07-28 07:53:10,414 - INFO - Upgrading/Installing 'hare' on '['srvnode-1']'
2021-07-28 07:53:21,207 - …
```

EOS-23138: CSM GUI is not accessible after upgrade

---

csm/cli/schema/users.json

- [EOS-23043](https://jts.seagate.com/browse/EOS-23043)
- User is not able to change role of CSM user using admin login. The following error occurs: Error:- Invalid request body: {'role': ['Not a valid string.']}
- In CORTXCLI configuration remove the 'append' logiv for the role parameter of the User update command
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes, tested manually
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ Yes, smoke test
- _PR is …

EOS-23043: fix role for User update command in cortxcli

---

csm/conf/cleanup.py
csm/conf/reset.py
csm/conf/setup.py

https://jts.seagate.com/browse/EOS-23259
Unable to start GUI after Reset phase.
csm_middleware.log was not able to create, as access denied issue observed.
Modifications in Reset phase:
- Only user created data removed.
- Log files reset done..Not removed.
- Unsupported feature cleanup removed.
Modifications in Cleanup phase:
- Setup created data and config removed.
- Log files directory removed.
- Unsupported feature cleanup.
- _Coding conventions are followed and code is consistent. Yes/No?_Y
- _Confirm All CODACY errors are resolved. Yes/No?_Y
```
[root@ssc-vm-rhev4-0307 csm]# csm_setup post_install --config json:///opt/seagate/cortx_configs/provisioner_cluster.json
:PASS
[root@ssc-vm-rhev4-0307 csm]# csm_setup …
```

EOS-23259: CSM GUI fails to start after Reset

---

csm/cli/schema/csm_setup.json
csm/conf/cleanup.py
csm/conf/reset.py
csm/conf/setup.yaml
csm/core/blogic/const.py

https://jts.seagate.com/browse/EOS-22899
Create Pre-factory interfacr in Cleanup phase for  csm-setup
- Pre-factory flag to be added to Cleanup phase
- Pre-factory will take system back to pre-factory stage i,e. Before post-install phase
- For csm_setup, prefactory will 
-- cleanup the service file
-- Remove service user in Dev mode only.
- Other functionalities of cleanup will run as it is
- _Coding conventions are followed and code is consistent. Yes/No?_Y
- _Confirm All CODACY errors are resolved. Yes/No?_Y
Add Pre-factory arg to cleanup command
```
[root@ssc-vm-rhev4-0906 731368]# csm_setup cleanup --help
usage: csm_setup cleanup [-h] [--config CONFIG_URL] [--pre-factory]
optional arguments:
-h, --help           show …
```

EOS-22899: F-97D: cleanup pre-factory- csm_agent

---

csm/conf/cleanup.py
csm/conf/configure.py
csm/conf/reset.py
csm/conf/setup.py

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_NA
Reset Phase:
- Cleanup Consul db
- Re create Cluster admin with default password from Confstore.
Cleanup Phase:
- Cleanup all consul data..including CLuster admin  
- _Coding conventions are followed and code is consistent. Yes/No?_Y
- _Confirm All CODACY errors are resolved. Yes/No?_Y
```
[root@ssc-vm-rhev4-0906 731368]# csm_setup post_install --config json:///opt/seagate/cortx_configs/provisioner_cluster.json
:PASS
[root@ssc-vm-rhev4-0906 731368]#  csm_setup prepare --config json:///opt/seagate/cortx_configs/provisioner_cluster.json
:PASS
[root@ssc-vm-rhev4-0906 731368]# csm_setup config --config json:///opt/seagate/cortx_configs/provisioner_cluster.json -f
:PASS …
```

Reset and Cleanup Modificaitons for cluster admin feature

---

csm/common/filter.py

- Overview: EOS-22891:LIKE filter for Elasticsearch queries
- Currently the cortx-utils data framework does not support 'LIKE' operator for partial search. Elasticsearch supports full-text search which is used.
- Implementation of like operator for StringType is implemented in py-utils [#444](https://github.com/Seagate/cortx-utils/pull/444)
- _Coding conventions are followed and code is consistent. Yes/No?_: yes
- _Confirm All CODACY errors are resolved. Yes/No?: No 
- _Confirm Testing was performed with installed RPM. Yes/No?_:  Yes
- _Confirm all the …

EOS-22891:  LIKE filter for ElasticSearch queries 

---

cicd/csm_agent.spec
csm/conf/post_install.py
csm/conf/setup.py
csm/core/blogic/const.py

- [EOS-24103](https://jts.seagate.com/browse/EOS-24103)
- Remove systemd configuration from csm_setup.
- Make the SystemD configuration conditional basing on the Confstore key value (details are in JIRA).
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes, smoke test
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ Y
- _PR is self-reviewed? Yes/No?_ Yes
- _Jira is updated_ Yes
-  _Check if the description is clear and explained._ …

EOS-24103: Remove the SystemD dependency

---

csm/common/timeseries.py

EOS-23135: Passing invalid interval parameter in the GET stats query returns 200
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_Y
Passing invalid interval parameter in the GET stats query returns 200, it should return 400 response code.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ No
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_ No
- _Confirm Testing was …

EOS-23135: Passing invalid interval parameter in the GET stats query returns 200

---

csm/cli/schema/support_bundle.json

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>
- cortxcli support_bundle CLI should invoke utils code
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Y
-  https://jts.seagate.com/browse/EOS-24887
- _Describe the problem this patch intends to solve._ Currently Cortxcli support_bundle code pointing to CSM, should be redirected to utils code
- _For Bug describe the fix here._ NA
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_ N
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ NA
- _Confirm Test Cases cover Happy …

EOS-24887: cortxcli support_bundle CLI should invoke utils code.

---

csm/core/services/s3/utils.py

https://jts.seagate.com/browse/EOS-25510
Unable to communicate with s3 on https with self-signed certificate
Csm code not checking ssl-context

EOS-25510: Unable to communicate with s3 on https with self-signed certificate

---

experiments/audit_logs/audit_logs.py
experiments/audit_logs/log_store_collection.py

https://jts.seagate.com/browse/EOS-25529
POC for Audit log storage 
Idea is to provide support to audit logs when Elastic search is not available in LC
POC for audit log storage in File and Consul storage.
Adaptor pattern is used which is similar to KV store which is already utilized in Py-Utils
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/770670731/POC+-+CSM+Audit+Logs

EOS-25529: POC for CSM Audit logs

---

csm/core/agent/api.py

Handle  error 500 raised deu to s3 problem
Handle ClientConnectionError and Timeout Error and raise as 503 
Handling 503 incase of
1. Incorrect PORT number, which throwa TimeoutError
2. Incorrect HOST, which throws ClientConnectionError

EOS-25584: Raise 503 instead of 500 for s3 operations

---

csm/cli/schema/csm_setup.json
csm/conf/csm_setup.py
csm/conf/setup.yaml
csm/conf/upgrade.py

- Expose Upgrade interface for csm_setup
- https://jts.seagate.com/browse/EOS-26712
Exposing Upgrade interface for csm-setup. No implemetetion for now

EOS-26712: Expose Upgrade interface for csm_setup

---

csm/core/services/users.py

- [EOS: 26603](https://jts.seagate.com/browse/EOS-26603)
-  While editing role of last admin user it is throwing wrong error message.
-  User_role must be extract properly with correct name. 

EOS-26603 : Wrong error code and message for while editing role of last admin user

---

csm/core/services/s3/accounts.py

- CSM REST: Create S3 account failed with 500 ('InternalFailure' is not a valid IamErrors)
-  Added a wait of 3 seconds between create account and create login profile to let openldap replicate the data.
Signed-off-by: Shri Metta <shri.metta@seagate.com>

EOS-26124: Create S3Account failure fix

---

csm/conf/configure.py
csm/conf/init.py
csm/conf/post_install.py
csm/conf/prepare.py
csm/conf/setup.py
csm/core/services/sessions.py

- https://jts.seagate.com/browse/EOS-27191
- Commented the S3 login mechanism
- Removed is_K8s check from Miniprovisioing phases
Miniprovisioing Pass
Configuration Files
S3 login shows 401: Unautharized
Csm Login Sucessfull

EOS-27191: Remove S3 user login through management API & Remove is_k8s check from miniprovisioing phases

---

csm/core/agent/api.py

- REST APIs returns aiohttp and python versions as server header, even if users are unauthorized
-  Set Server header field to NULL
Signed-off-by: Shri Metta <shri.metta@seagate.com>

EOS-26753: [REST API] REST APIs returns aiohttp and python versions as server header, even if users are unauthorized.

---

csm/cli/support_bundle/csm_bundle_generate.py

-[EOS-28031](https://jts.seagate.com/browse/EOS-28031) - Support bundle enhancement for adding time filter
#NOTE: Below are the additional arguments, that all component specific Support Bundle script should accept.
Testcase 1 (Only Duration Filter): - csm agent logs are filtered based on the Duration filter
TestCase 2: Support bundle with Size and Duration Filter
Testcase 3: Support Bundle generation for Cortex

EOS-28031: Support bundle enhancement for adding time filter

---

csm/core/controllers/rgw/s3/users.py
schema/roles.json

[CORTX-28923: CRUD API operation should throw "InvalidKey" error with invalid parameters.(IAM users)](https://jts.seagate.com/browse/CORTX-28923)
Earlier any random keys in request body params were getting excluded. Now we are raising validation error for unknown keys in request body so that user will get to know he/she has given wrong body params.
#Tesing Screenshots
1. Unknown Field error
2. 201 response for user creation

CORTX-28923: [RGW] Raising validation error for unknown fields in IAM APIs

---

csm/plugins/cortx/rgw.py

- Per Ujjwal's request RGWAdminClient class is renamed to S3SignedClient.
-  Rename RGWAdminClient to S3SignedClient
-  Rename RGWAdminClientException to S3SignedClientException
- Update imports from `cortx.utils.rgwadmin` to `cortx.utils.s3`

F45I: rename RGWAdminClient to S3SignedClient

---

csm/core/agent/api.py
csm/core/controllers/storage_capacity.py
csm/core/services/storage_capacity.py

Updated endpoint from /api/v2/cluster/status/bytecount to /api/v2/capacity/status/bytecount
Expose REST API for fetching Degraded Object Byte count
Update status api to query for bytecount : https://github.com/Seagate/cortx-manager/pull/767
- Jira [CORTX-28027](https://jts.seagate.com/browse/CORTX-28027)
[Design document](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/852000897/F-71E+-+Management+Capacity+Get+Degraded+Capacity+in+Byte+count)

CORTX-28027:Update status api to query for bytecount

---

csm/core/controllers/rgw/s3/users.py

- [CORTX-29496:PATCH iam user request passes with null values for editable parameters](https://jts.seagate.com/browse/CORTX-29496)
Required parameters are must have in the request body and their value should be valid too, else response will be 400 Bad Request.
If user giving optional parameter in the request body then value of the same should be valid one, null value will return  back '400 Bad Request'  response to user.
step1: Create IAM user.
step2: Modify the same IAM user. Check validation against null …

CORTX-29496: Modify IAM User API validation fix

---

cicd/build.sh
csm/conf/configure.py

- [CORTX-29553](https://jts.seagate.com/browse/CORTX-29553): Move unsupported features related configurations to consul
-  Disable brand path for unsupported features to get the activate the proper unsupported features schema 
- Raise an exception in case unsupported features database is not accessible

CORTX-29553: Move unsupported features related configurations to consul

---

csm/conf/requirment.txt

- Problem statement
Current cryptography version is 2.8. This version has High/medium level vulnerabilities
This version is planned to be upgraded to 3.3.2
Thought process of upgrading to version 3.3.2 is as follows
Version upgrade for cryptography library from version 2.8 to version 3.3.2 is recommended by Whitesource vulnerability scanning tool.
There are several cryptography versions available which are higher than 3.3.2. However further library package upgrade will be planned in subsequent iteration,
-  [X] Coding conventions are followed and code is consistent
Detailed manual and regression testing is complete and test results are uploaded to this story …

CORTX-29993: Update cryptography library from 2.8 to 3.3.2

---

csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/services/session/session_factory.py
csm/core/services/sessions.py

- [CORTX-30331](https://jts.seagate.com/browse/CORTX-30331): active users quota.
- Restrict the number of active CSM users to be no more than the provided quota.
-  Extend the `SessionManager` functionality by introducing the successor class `QuotaSessionManager`
- Keep in-memory statistics of logged-in users and number of sessions per user `{user_id: <number of sessions>}`
- Restore the statistics from the storage at the first session creation request, populate at each login and logout
- Try to clear the storage from expired sessions when the new session doesn't fit the quota.

CORTX-30331: active users quota

---

csm/core/controllers/rgw/s3/base.py
csm/core/controllers/rgw/s3/bucket.py
csm/core/controllers/rgw/s3/users.py

- CORTX-31374: Remove purge_data option support while deleting an IAM user and restrict the operations on internal IAM user
-   \[x] JIRA number/GitHub Issue added to …

CORTX-31374: Remove the support of purge_data attribute from IAM user delete API.

---

csm/conf/requirment.txt

Signed-off-by: swanand-gadre <swanand.s.gadre@seagate.com>
Paramiko package 2.7.X is vulnerable.
It needs to be upgraded to version 2.10.4
This PR is raised to upgrade this version.
This PR is raised to upgrade paramiko package from 2.7.X to 2.10.4
-   \[X] Coding conventions are followed and code is consistent
-   \[X] Unit and System Tests are added
-   \[X] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[X] Testing was performed with RPM
All test details are available in a document attached to this ticket -> https://jts.seagate.com/browse/CORTX-30265
-   \[X] Interface change …

CORTX-30265 - paramiko upgrade to 2.10.4

---

csm/core/services/storage_capacity.py
csm/plugins/cortx/rgw.py
schema/iam_operations_mapping.json

-   [Get user capacity API should throw 'NoSuchUser' for non existing user](https://jts.seagate.com/browse/CORTX-32075)
-   \[x] JIRA number/GitHub Issue added to …

CORTX-32075: Fixed: Get user capacity API should throw 'NoSuchUser' for non existing user.

---

csm/conf/configure.py
csm/core/services/sessions.py

-   Need to have only 1 session per user
-  Update formulae to update calculation of request quota
-   At the time of successful login, check if valid session exists, if yes, return that session or create a new session and return
- Formulae :- (quota =  MaxAvailableMemForRequest/ RequestSize)
- [Custom Build job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6689/)
- Custom Build
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6689-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6689-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6689-custom-ci
-  [ Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/)
Admin Login from Client Machine
Admin …

CORTX-30330: Resource Quota Update

---

csm/core/agent/api.py

-   [CORTX-31607](https://jts.seagate.com/browse/CORTX-31607): REST API returns aiohttp and python versions as server header for authorized users.
-   On `aiohttp` signal remove 'Server' header before the response is sent.
-   \[x\] Coding conventions are followed and code is consistent
-   \[x\] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[x\] Testing was performed with RPM
-   \[x\] JIRA number/GitHub Issue added to PR
-   \[x\] PR is self reviewed
- …

CORTX-31607: hide 'Server' HTTP header in responses

---

csm/core/agent/csm_agent.py
csm/core/controllers/users.py
csm/core/services/users.py

-   [CORTX-33726](https://jts.seagate.com/browse/CORTX-33726): Able to create 101th CSM user
-   Guard create_user mehtod with asyncio.Lock to prevent race condition between getting the current number of users and creating a new one.
-   \[x\] Coding conventions are followed and code is consistent
-   \[\] Unit and System Tests are added
-   \[ \] PR is self …

CORTX-33726: fix race condition on users quota check

---

csm/conf/setup.py
test/user_management/test_api_functional_requirements.py

-   User service constructor definition has changed in #878 causing mini-prov failure.
-   Fixed the user service call while creating cluster admin user during mini-prov 
-   \[x] PR is self …

CORTX-33835: Fix CSM mini-provisioning failure

---

csm/conf/configure.py
csm/conf/csm_default.conf
csm/conf/etc/csm/csm.conf
csm/conf/init.py
csm/core/agent/api.py
csm/core/blogic/const.py

-   [Handle Resource Limit configuration during mini-provisioning to work with consul](https://jts.seagate.com/browse/CORTX-33879)
- Problem here is - 
CSM is trying to read Limits conf dict  from gconf, and consul based gconf doesnt support this. 
- Solution,
Iterate over the list and create key structure and fetch the config. …

CORTX-33879: Fixed errors while fetching resource limit conf from consul confstore

---

csm/common/cluster.py
csm/common/conf.py
csm/common/fs_utils.py
csm/common/timeseries.py
csm/conf/configure.py
csm/conf/csm_setup.py
csm/conf/init.py
csm/conf/post_install.py
csm/conf/prepare.py
csm/core/agent/api.py
csm/core/agent/csm_agent.py
csm/core/blogic/email_conf.py
csm/core/controllers/users.py
csm/core/data/models/session.py
csm/core/providers/providers.py
csm/core/services/permissions.py
csm/core/services/sessions.py
csm/core/services/stats.py
csm/core/services/users.py
test/service/test_csm_service.py
test/user_management/test_api_functional_requirements.py

-  [Codacy Baseline for code pattern, reduce Issues & false positive](https://jts.seagate.com/browse/CORTX-33159)
-   \[x] PR is self reviewed
-   \[x] Jira and state/status is updated and JIRA is …

CORTX-33159: Codacy Fix

---

csm/core/controllers/information.py
csm/core/services/information.py

-   Handle negative scenarios as per [REST SPECIFICATION](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1024229377/Query+Deployment+REST+API+specification)
-  Invalid resource
- Invalid resource id
-   \[ \] …

CORTX-33846: Integration with provisioner for query deployment

---

csm/core/services/storage_capacity.py
schema/iam_operations_mapping.json

-   [Tenant details are missing in the ID field of the GET capacity](https://jts.seagate.com/browse/CORTX-32589)
- …

CORTX-32589: [Bug fix] Fixed mapping in capacity response

---

csm/core/controllers/storage_capacity.py

-  [Rest API implementation to handle tenant details for Capacity API](https://jts.seagate.com/browse/CORTX-33950)
- …

CORTX-33950: GET IAM user capacity API with tenant as a path param

---

csm/core/blogic/const.py

-  Jira id: [CORTX-33861]( https://jts.seagate.com/browse/CORTX-33861)
- 
-  CSM uses S3client to send request to RGW.. which has timeout parameter value set to 20 seconds
- RGW might take more than 20 seconds to execute create IAM user request which lead to TIMEOUT error
- By increasing timeout value we can execute 122 requests. 
- Build:
concurrent requests:
122 successful requests:
-   \[ \] Interface change (if any) are …

CORTX-33861: Create IAM user fails with 408 RequestTimeout

---

csm/core/agent/api.py

- CORTX-34105
-   Due to throttler middleware logs modified in #895, agent is throwing 500 instead of 429 incase of no. of request exceeding CSM request-quota.
-   \[x] PR is self reviewed
-   \[x] …

CORTX-34105: [Fixed] Invalid status code incase of rejected requests by csm-agent

---

csm/core/data/models/rgw.py
csm/core/services/query_deployment/topology_factory.py

-    Jira: [CORTX-34185](https://jts.seagate.com/browse/CORTX-34185)
Updated document:
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1024229377/Query+Deployment+REST+API+specification
- 
-   \[ \] JIRA number/GitHub Issue …

CORTX-34185: Incorrect data and metadata storage set values in the query deployment response
