Seagate/cortx-manager

csm/cli/schema/support_bundle.json

<pre>
<code>
Story Ref (if any): EOS-13631
Incorrect help for support_bundle generate command
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Incorrect help for support_bundle generate command
</code>
</pre>
<pre>
<code>
Corrected help string for suppot_bundle generate 
</code>
</pre>
<pre>
<code>
Locally Tested
</code>
</pre>

[Cortx] resolve EOS-13631 Corrected help string for support_bundle generate

---

csm/conf/csm_cleanup.py
csm/conf/etc/cron.daily/es_logrotate.cron
csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Resolves https://jts.seagate.com/browse/EOS-13396
Moved statsd cleanup to cron.daily es_log_cleanup
</pre>
<pre>
Done
</pre>
<pre>
</pre>
<pre>
Moved statsd cleanup to cron.daily es_log_cleanup
</pre>
<pre>
Triggered csm_cleanup manually for stats
</pre>

[CORTX] resolve Eos 13396 Moved entry for statsd cleanup also into es_logrotate.cron

---

csm/conf/setup.py

<pre>
<code>
Story Ref (if any): EOS-
As Per discussion Fixing the Provisioner API on 2ndary node.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
As Per discussion Fixed the Provisioner API on 2ndary node. by Handling Exceptions.
</code>
</pre>
<pre>
<code>
Not Tested
</code>
</pre>

Setup fix cortx

---

csm/conf/csm_cleanup.py
csm/conf/etc/cron.daily/es_logrotate.cron
csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Resolves https://jts.seagate.com/browse/EOS-13396
Moved statsd cleanup to cron.daily es_log_cleanup
</pre>
<pre>
Done
</pre>
<pre>
</pre>
<pre>
Moved statsd cleanup to cron.daily es_log_cleanup
</pre>
<pre>
Triggered csm_cleanup manually for stats
</pre>

[main] resolve Eos 13396 Moved entry for statsd cleanup also into es_logrotate.cron

---

csm/core/controllers/view.py

EOS-13605- LDR is failed to update
No
LDR is failed to update as /tmp/csm/file_cache/transfer does not exists (might be deleted at some point)
Added code to create dirs /tmp/csm/file_cache/transfer
Tested on local VM

[Main] EOS-13605: LDR is failed to update

---

csm/cli/cortxcli.py
csm/cli/support_bundle/bundle_generate.py

<pre>
<code>
Changes for Support Bundle to read rc rather than err messages.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Need to remove the changes for Support Bundle and  remove decryption from cortxcli
</code>
</pre>
<pre>
<code>
Made the changes as required.
</code>
</pre>
<pre>
<code>
Locally Tested
</code>
</pre>

[[CORTX] Encryption fix cortx for rodi

---

csm/conf/setup.py

Check-in https://github.com/Seagate/cortx-manager/pull/126 into Cortx-1.0.

Csm agent restart correction

---

csm/conf/setup.py

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>

setup info upper

---

csm/core/controllers/usl.py
csm/core/services/s3/accounts.py
csm/core/services/usl.py

<pre>
Story Ref (if any): EOS-14045
</pre>
<pre>
</pre>
<pre>
The main PR for EOS-14045 (https://github.com/Seagate/cortx-manager/pull/180) was merged before @tb-s was able to review it. This PR includes amendments required on the CR.
</pre>
<pre>
Addressing all issues in https://github.com/Seagate/cortx-manager/pull/180
</pre>
<pre>
None
</pre>

[CORTX1.0] EOS-14045: CR notes and amendments

---

csm/core/controllers/usl.py
csm/core/services/s3/accounts.py
csm/core/services/usl.py

* EOS-14045: process CR notes
Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>
* EOS-14045: remove excess access keys service from USL
Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>
* EOS-14045: correct exception handling in the UDX registration sequence
Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>
<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

[CORTX1.0] EOS-14045: CR notes and amendments (#191)

---

csm/cli/schema/bundle_generate.json
csm/cli/schema/support_bundle.json
schema/commands.yaml

Signed-off-by: Ajay Paratmandali <ajay.paratmandali@seagate.com>
<pre>
https://jts.seagate.com/browse/EOS-14006
</pre>
<pre>
Yes
</pre>
<pre>
Support bundle for ha is missing
</pre>
<pre>
Add ha support bundle in cortxcli
</pre>
<pre>
Integration testing is done
No unit testing available.
</pre>
Signed-off-by:

Support Bundle for ha

---

csm/core/blogic/const.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Moved csm logrotate conf file to /etc/logrotate.d (#219)

---

cicd/auxiliary/install_csm.sh

<pre>
Story Ref (if any): EOS-14381 - Remove dependency on hare for consul
</pre>
<pre>
No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>

EOS-14381: Remove dependency on hare for consul

---

cicd/auxiliary/install_csm.sh
csm/cli/support_bundle/csm_bundle_generate.py
csm/conf/etc/csm/csm.conf
csm/core/blogic/const.py
csm/plugins/cortx/provisioner.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Cortx1.0 dev

---

csm/core/blogic/const.py
csm/plugins/cortx/provisioner.py

<pre>
</pre>
<pre>
Yes
</pre>
<pre>
Description CSM init is not working
</pre>
<pre>
Removed Conf.save() from provisioner.py
</pre>
<pre>
</pre>

Removed Conf.save() from provisioner.py

---

cicd/build.sh

<pre>
</pre>
<pre>
Yes
</pre>
<pre>
Build is failing for LDR build.
</pre>
<pre>
Change the position to copy the files
</pre>
<pre>
NA
</pre>

Brand build fix

---

csm/cli/support_bundle/support_bundle.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14577
</pre>
<pre>
Yes
</pre>
<pre>
Incorrect error message 
</pre>
<pre>
error(111): Bundle status failed to connect to elasticsearch.
</pre>
<pre>
[root@ssc-vm-1283 721542]# systemctl stop elasticsearch.service
[root@ssc-vm-1283 721542]# cortxcli support_bundle status SBz1mnn1en
error(111): Bundle status failed to connect to elasticsearch.
[root@ssc-vm-1283 721542]#
</pre>
Signed-off-by:

[Cortx-dev] EOS-14577 Handle exception for bundle status

---

csm/cli/support_bundle/csm_bundle_generate.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

EOS-14529-improvement-cortx-dev: Adding error message to alerts support bundle in case of exception.

---

csm/conf/etc/csm/csm.conf
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/appliance_info.py
csm/core/controllers/routes.py
csm/core/services/appliance_info.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14529
Read Unique ID from file to Display
</pre>
<pre>
No
</pre>
<pre>
Add an API to show serial number on UI
</pre>
<pre>
Added an API to show serial number on UI
</pre>
<pre>
</pre>

[CORTX-DEV] EOS-14529-cortx-dev: Added an API to fetch serial number from a file

---

README.md

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

cortx-manager readme link fix

---

csm/conf/etc/csm/csm.conf
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/appliance_info.py
csm/core/controllers/routes.py
csm/core/services/appliance_info.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-14529
Read Unique ID from file to Display
</pre>
<pre>
No
</pre>
<pre>
Add an API to show serial number on UI
</pre>
<pre>
Added an API to show serial number on UI
</pre>
<pre>
</pre>

[MAIN] EOS-14529: Added an API to fetch serial number from a file

---

csm/core/agent/api.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py

<pre>
Story Ref (if any):https://jts.seagate.com/browse/EOS-14780
</pre>
<pre>
Yes
</pre>
<pre>
usl audit log were not getting filter in success case
</pre>
<pre>
Added filter call in success case also
</pre>
<pre>
Testing done on VM
</pre>
Signed-off-by:

[cortx-dev] EOS-14780  usl polling log filtering in case of success also

---

csm/common/ha_framework.py
csm/conf/etc/csm/csm.conf

<pre>
Story Ref (if any):EOS-14583
Shutdown not working using GUI or CLI.
</pre>
<pre>
Yes
</pre>
<pre>
System is not getting shutdown either from GUI nor from CLI. Since the cronjobs is not executing the command.
</pre>
<pre>
Updated the Cron Time to 2 minutes to check the cron issues
</pre>
<pre>
None
</pre>
Signed-off-by: <prathamesh.rodi@seagate.com>

EOS-14583 Changing Cron Time to 120 seconds to remove cron time.

---

CONTRIBUTING.md
CORTXManagerQuickstartGuide.md

Updated CORTXManagerQuickstartGuide.md
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>

Updated CORTXManagerQuickstartGuide.md

---

csm/conf/setup.py
csm/core/blogic/const.py

Please check [the corresponding ticket](https://jts.seagate.com/browse/EOS-15160) and [this comment](https://jts.seagate.com/browse/EOS-15160?focusedCommentId=1983875&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1983875) for details.

[cortx-1.0] EOS-15160: M5: Build #463: deploy replacement fail at "components.csm.config"

---

csm/common/comm.py
csm/core/agent/csm_agent.py
csm/core/services/alerts.py
csm/core/services/health.py
csm/plugins/cortx/alert.py
csm/plugins/cortx/health.py

<pre>
Improve csm logs during shutdown
Story Ref (if any): https://jts.seagate.com/browse/EOS-14853
</pre>
<pre>
No
</pre>
<pre>
Improve csm logs during shutdown
</pre>
<pre>
Added logs at INFO level
</pre>
<pre>
</pre>

EOS-14853-log-improvement: Improved logs during CSM shutdown

---

csm/common/ha_framework.py
csm/conf/etc/csm/csm.conf

<pre>
Story Ref (if any):EOS-14583
Shutdown not working using GUI or CLI.
</pre>
<pre>
Yes
</pre>
<pre>
System is not getting shutdown either from GUI nor from CLI. Since the cronjobs is not executing the command.
</pre>
<pre>
Updated the Cron Time to 2 minutes to check the cron issues
</pre>
<pre>
None
</pre>
Signed-off-by: <prathamesh.rodi@seagate.com>

EOS-14853  Shutdown not working using GUI or CLI.

---

csm/core/services/alerts.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

typo-fix: Fixed a typo

---

csm/cli/support_bundle/csm_bundle_generate.py
csm/conf/etc/csm/csm.conf
csm/core/services/alerts.py

<pre>
<code>
Elaseticsearch Logs are skipped even if one file is missing.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
If even One file is missing elasticsearch logs are not bundled in Support Bundle.
</code>
</pre>
<pre>
<code>
Fixed the code and Updated the Changes.
</code>
</pre>
<pre>
<code>
Unit Testing details here...
</code>
</pre>
<pre>
<code>
Yes/No
</code>
</pre>
<pre>
<code>
Update Cli Command Help Section....
</code>
</pre>
<pre>
<code>
Update Cli Expected Output Here.... 
</code>
</pre>

EOS-15294  ES support bundle is not created.

---

csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Reduce the amount of data for virtual appliance setup.
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
Apply different logrotation configuration for virtual applicances.
</pre>
<pre>
- run `csm_setup init` on the virtual appliance. 
</pre>

EOS-13349: Reduce the amount of data for virtual appliance setup

---

cicd/auxiliary/etc/database.json
csm/cli/conf/etc/cli/database_cli.yaml
csm/conf/etc/csm/database.yaml
csm/conf/setup.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Eos 15055 update

---

cicd/build.sh

<pre>
Testing Build Issue For Numpy
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Moving numpy install uninstall

---

csm/cli/conf/etc/cli/cortxcli.conf
csm/cli/cortxcli.py
csm/cli/scripts/system.py
csm/cli/support_bundle/support_bundle.py
csm/common/ha_framework.py
csm/conf/etc/csm/csm.conf
csm/conf/setup.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py

<pre>
Story Ref (if any): EOS-15665
Security: disable SSH or ensure strong passwords for all service accounts
</pre>
<pre>
No
</pre>
<pre>
CSM Hardcoded Password are visible in Opensource Hence we will be fetching a randomly generating password.
</pre>
<pre>
Changes made for fetching code from provisioner and saving encrypted randomly generated password.
</pre>
<pre>
</pre>
Signed-off-by:

EOS-15665 Changes for CSM User Password Being Fetched From Provisioner.

---

cicd/auxiliary/etc/database.json
csm/cli/conf/etc/cli/database_cli.yaml
csm/conf/etc/csm/database.yaml
csm/conf/setup.py

Reverts Seagate/cortx-manager#320

Revert "Update for EOS-15055"

---

cicd/auxiliary/csm_cicd.sh

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

EOS-16587  CSM RE Build Changes in Script.

---

csm/conf/configure.py
csm/conf/init.py
csm/conf/post_install.py
csm/conf/refresh_config.py
csm/conf/setup.py
csm/core/blogic/const.py
templates/csm_setup_conf_template.json

<pre>
Story Ref (if any): EOS-16153
CSM Mini Provisioner
</pre>
<pre>
No
</pre>
<pre>
Changes in Keys that are supposed to be received from Provisioner.
</pre>
<pre>
Made the Changes in all the Keys as per the Config Store Keys Provided by Provisioner.
</pre>
<pre>
Unit Test is Dependent once Provisioner Integration is to Be Done and Provisioner conf store file is ready.
</pre>

EOS-16153 Changes in keys as per Provisioner Conf Store File.

---

csm/core/controllers/s3/accounts.py
csm/core/controllers/s3/iam_users.py
csm/core/services/s3/accounts.py
csm/core/services/s3/iam_users.py
csm/plugins/cortx/s3.py
schema/roles.json

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-16595
</pre>
<pre>
Tested manually
</pre>
<pre>
See story for details.
</pre>
<pre>
- For S3 account - remove boundaries to update account's login profile when logged in as CSM user;
- For IAM user - implement API to update user's login profile when logged in as an S3 account user.
</pre>
<pre>
- Log in as CSN user, try to reset password of the S3 account;
- Log in as an S3 account, try to reset password of the IAM user.
</pre>

EOS-16595: Reset S3 account's password; reset IAM user's password

---

csm/core/blogic/const.py
csm/core/controllers/routes.py
csm/core/controllers/security.py
csm/core/services/security.py

<pre>
Story Ref (if any): EOS-16584
</pre>
<pre>
Yes
</pre>
<pre>
Fetch SSL information
</pre>
<pre>
1. Added a method in services/security.py to fetch SSL information from .pem file
2. Added API in controllers.services.py to get the details
</pre>
<pre>
Manually tested on RPM
Response:
{
"cert_details": {
"subject": {
"commonName": "localhost",
"countryName": "US",
"localityName": "Denver",
"stateOrProvinceName": "Colorado",
"organizationName": "Seagate",
"organizationalUnitName": "CSM"
},
"issuer": {
"commonName": "CSM",
"countryName": "US",
"localityName": "Voronezh",
"stateOrProvinceName": "Colorado",
"organizationName": "Seagate",
"organizationalUnitName": "CSM",
"emailAddress": "csm_root_ca@mail.com"
},
"not_valid_after": "2033-10-14 16:29:14",
"not_valid_before": "2020-02-05 …

EOS-16584: Fetch SSL information

---

csm/conf/configure.py
csm/conf/init.py
csm/conf/post_install.py
csm/conf/refresh_config.py
csm/conf/setup.py
csm/conf/setup.yaml

<pre>
</pre>
<pre>
Yes
</pre>
<pre>
Need to Fix the Import From Kvstore to kv_store for KVError Class.
</pre>
<pre>
Made changes in Import
</pre>
<pre>
Not Required.
</pre>
Signed-off-by:

Fixing Import for KV Store KV error

---

csm/cli/schema/csm_setup.json
csm/conf/csm_setup.py
csm/conf/setup.yaml
csm/conf/test.py

<pre>
Story Ref (if any): EOS-17010
Integrate CSM mini Provisioner with CSM.
</pre>
<pre>
Yes
</pre>
<pre>
Need to make Changes to TEST Command and Setup.yaml for CSM and Fix the Changes.
</pre>
<pre>
Made the Changes as Discussed With Nitin.
</pre>
<pre>
Fix for Unit test Case Only so not Seperate Test Cases.
</pre>

EOS-17010 Changes foe CSM Setup and Test Command for CSM Mini Provisioner.

---

csm/conf/setup.yaml

<pre>
Story Ref (if any): EOS-17010 
Fixing Setup.yaml error caused in Merge.
</pre>
<pre>
Yes
</pre>
<pre>
Setup.yaml was changed due to Merge Issues in CSM Branchs as required by Provisioner
</pre>
<pre>
Fixed CSM Setup.yaml as per Mini Provisioner Requirements.
</pre>
<pre>
NA
</pre>
Signed-off-by:

EOS-17010 Changes for Fix issues caused in Merge

---

csm/plugins/cortx/alert.py
schema/alert_mapping_table.json

<pre>
Story Ref (if any): EOS-17432: Unexplained "cpu|fault" and "psu_fault|resolved" events
</pre>
<pre>
Yes
</pre>
<pre>
Unexplained "cpu|fault" and "psu_fault|resolved" events
</pre>
<pre>
Updated the description field mapping as per SSPL description.
</pre>
<pre>
</pre>
Signed-off-by:

EOS-17432: Unexplained "cpu|fault" and "psu_fault|resolved" events

---

cicd/pyinstaller/requirment.txt

Reverts Seagate/cortx-manager#394

Revert "EOS-17515 Cryptograpy Package Update."

---

csm/conf/uds.py

[EOS-17970: Build #578: SMS2: UDX overnight data movement stuck](https://jts.seagate.com/browse/EOS-17970)
No.
- Modify UDS configuration during `csm_setup config` step and decrease the number of sub workers from 24 (the default) to 4.
N/A.

EOS-17970: Configure number of UDS sub workers

---

csm/conf/setup.py
templates/csm_setup_conf_template.json

<pre>
Story Ref (if any): NA
</pre>
<pre>
Yes
</pre>
<pre>
Unable to set Deployment mode:DEV
</pre>
<pre>
Incorrect template for mini provisioning
</pre>
Signed-off-by:

Resolving Deployment Mode on Single Node Dev VM

---

csm/cli/schema/alerts.json

Signed-off-by: srikant.vishwakarma@seagate.com
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-18963
</pre>
<pre>
Yes
</pre>
<pre>
Make changes to consume the new alert schema .
</pre>
<pre>
Added hostname mapping in alerts schema.
</pre>
<pre>
Tested on cortxcli
</pre>

EOS-18963: Make changes to consume the new alert schema

---

csm/cli/schema/alerts.json
csm/cli/schema/email.json
csm/cli/schema/s3accesskeys.json
csm/cli/schema/s3accounts.json
csm/cli/schema/s3bucketpolicy.json
csm/cli/schema/s3buckets.json
csm/cli/schema/s3iamusers.json
csm/cli/schema/security.json
csm/cli/schema/system.json
csm/cli/schema/users.json

<pre>
</pre>
[EOS-18913 : Update cli to call version v2 of REST APIs](https://jts.seagate.com/browse/EOS-18913)
<pre>
No
</pre>
<pre>
Update cli to call version v2 of REST APIs
</pre>
<pre>
Updated all CLI schemas to call version 2 REST APIs.
</pre>
<pre>
</pre>

CLI: Update cli to call version v2 of REST APIs

---

csm/conf/csm.config.tmpl.1-node
csm/conf/csm.config.tmpl.1-node.sample
csm/conf/csm.config.tmpl.3-node
csm/conf/csm.config.tmpl.3-node.sample
csm/conf/csm.init.tmpl.1-node
csm/conf/csm.init.tmpl.1-node.sample
csm/conf/csm.init.tmpl.3-node
csm/conf/csm.init.tmpl.3-node.sample
csm/conf/csm.post_install.tmpl.1-node
csm/conf/csm.post_install.tmpl.1-node.sample
csm/conf/csm.post_install.tmpl.3-node
csm/conf/csm.post_install.tmpl.3-node.sample
csm/conf/csm.prepare.tmpl.1-node
csm/conf/csm.prepare.tmpl.1-node.sample
csm/conf/csm.prepare.tmpl.3-node
csm/conf/csm.prepare.tmpl.3-node.sample
csm/conf/setup.yaml

<pre>
Story Ref (if any):NA
</pre>
<pre>
No
</pre>
<pre>
Removing old ha entries from setup.yaml
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Updating setup.yaml and conf templates

---

csm/common/conf.py
csm/conf/csm.config.tmpl.1-node
csm/conf/csm.config.tmpl.1-node.sample
csm/conf/csm.config.tmpl.3-node
csm/conf/csm.config.tmpl.3-node.sample
csm/conf/csm.init.tmpl.1-node
csm/conf/csm.init.tmpl.1-node.sample
csm/conf/csm.init.tmpl.3-node
csm/conf/csm.init.tmpl.3-node.sample
csm/conf/csm.prepare.tmpl.1-node
csm/conf/csm.prepare.tmpl.1-node.sample
csm/conf/csm.prepare.tmpl.3-node
csm/conf/csm.prepare.tmpl.3-node.sample
csm/conf/etc/csm/csm.conf
csm/conf/prepare.py
csm/conf/setup.py
csm/core/blogic/const.py

<pre>
Story Ref (if any): NA
</pre>
<pre>
Yes
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

EOS-19502:Modifications in csm_setup as per discussed in warroom

---

csm/conf/configure.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Adding localhost validation for ES and Consul in csm_setup configure

---

csm/core/controllers/s3/accounts.py

Signed-off-by: srikant.vishwakarma@seagate.com
<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19109
</pre>
<pre>
Yes
</pre>
<pre>
R2:User is getting logged out of CLI and UI after updating the password for s3account user
</pre>
<pre>
Removed code for clear sessions.
</pre>
<pre>
No
</pre>

EOS-19109: R2 - User is getting logged out of CLI and UI after updating the password for s3account user

---

csm/conf/configure.py

<pre>
Story Ref (if any): https://jts.seagate.com/browse/EOS-19785
</pre>
<pre>
Yes
</pre>
<pre>
CSM component was failing at deployment deu to unsupported feature not able to communicate to ES in csm_setup config command 
</pre>
<pre>
Added the looping logic to retry the unsupported feature operation
</pre>
<pre>
We have tested our patch on vm in following sequence in an automated script which runs for 100 iterations..
Teardown CSM component -> salt '*' state.apply components.csm.teardown
Teardown Elasticsearch -> salt '*' state.apply components.misc_pkgs.elasticsearch.teardown
Deploy Elasticsearch component -> salt '*' state.apply components.misc_pkgs.elasticsearch
Deploy CSM component ->salt '*' state.apply …

Adding fix for ES issue.

---

csm/core/agent/csm_agent.py
csm/plugins/cortx/health.py

<pre>
</pre>
<pre>
No
</pre>
<pre>
Sometimes CSM was unable to initialize consumer.
</pre>
<pre>
The issue is due to thread synchronization. Added a delay to resolve.
</pre>
<pre>
</pre>
Signed-off-by:

consumer-failure-fix: Fixed connection related issues for messagebus

---

csm/common/timeseries.py
csm/conf/configure.py
csm/conf/post_install.py
csm/core/agent/api.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/blogic/models/audit_log.py
csm/core/controllers/audit_log.py
csm/core/controllers/s3/accounts.py
csm/core/services/appliance_info.py
csm/core/services/audit_log.py
csm/core/services/stats.py
csm/core/services/users.py
csm/plugins/cortx/health.py
csm/plugins/cortx/provisioner.py
csm/plugins/cortx/s3.py
schema/commands.yaml
schema/roles.json

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Merge Main to Stable

---

csm/conf/configure.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

Temporary blocking network validation  for Virtual IP

---

csm/conf/post_install.py

<pre>
</pre>
<pre>
Yes/No
</pre>
<pre>
</pre>
<pre>
</pre>
<pre>
</pre>
Signed-off-by:

t-main Updation

---

csm/common/errors.py

Reverts Seagate/cortx-manager#476

Revert "EOS-20752: Renaming BaseError class name to UtilsError"

---

csm/common/ha_framework.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/health.py
csm/core/controllers/routes.py
csm/core/services/health.py

<pre>
Story Ref (if any): EOS-20351: API for health
</pre>
<pre>
No
</pre>
<pre>
Create REST APIs for fetching health
</pre>
<pre>
Created REST APIs with stub classes and methods and integration will be done when API from HA will be ready.
</pre>
<pre>
No unit testing done as these are only stub classes and methods.
</pre>
Signed-off-by: Shri Metta <732880@ssc-vm-4708.colo.seagate.com>

EOS-20351: Added stub classes for Health API.

---

csm/common/ha_framework.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/health.py
csm/core/controllers/routes.py
csm/core/services/health.py
csm/plugins/cortx/health.py
schema/feature_endpoint_mapping.json
schema/unsupported_features.json

- EOS-21024: REST API implementation of resources health
- End to end REST API implementation of resources health
- _For feature, post the link to the solution page.
- https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/368574557/REST+API+Specification
- https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/380141918/CLI+Specification
- _Coding conventions are followed and code is consistent. Yes/No? Yes
- _Confirm All CODACY errors are resolved. Yes/No? Yes
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? No
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? No
- _Confirm …

EOS-21024: REST API implementation of resources health

---

csm/cli/schema/health.json

[EOS-20365: CLI: Node Health](https://jts.seagate.com/browse/EOS-20365)
- Add new command in cortxcli that will return the health of the cluster and the resources in it.
[Health CLI Specification](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/380141918/CLI+Specification)
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_ NA
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Testing was …

EOS-20365: Health on cortxcli

---

csm/core/services/iem.py
csm/core/services/security.py

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Y https://jts.seagate.com/browse/EOS-20374
- _Describe the problem this patch intends to solve. : CSM need to incorporate the changes done for sending and receiving IEMs. This patch handles 
- _For Bug describe the fix here._ NA
- _For feature, post the link to the solution page._ - https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735500/IEM+Framework
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_ N
- _Confirm that Test Cases are added (for both the cases, fix and feature). …

EOS-20374: New IEM framework implementation for producer

---

csm/core/agent/api.py

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-21195
- _Describe the problem this patch intends to solve._ The CSM audit logs are not showing up on the UI
- _For Bug describe the fix here._ Reverted code for initializing csmauditlog schema
- _Coding conventions are followed and code is consistent. Yes/No?_Yes
- _Confirm All CODACY errors are resolved. Yes/No?_Yes
- _Confirm Testing was performed with installed …

EOS-21195:Audit logs display bug fix

---

csm/common/ha_framework.py
csm/plugins/cortx/health.py

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]: Y
- 404 error should be returned if invalid resource is provided.
- _For Bug describe the fix here. Raising CsmNotFoundError if invalid resource is found.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: NA
- _Coding conventions are followed and code is consistent. Yes/No? Yes
- _Confirm All CODACY errors are resolved. Yes/No? Yes
- _PR is …

EOS-21406: Updated api error handling.

---

csm/cli/schema/health.json
csm/common/ha_framework.py
csm/conf/cleanup.py
csm/conf/configure.py
csm/conf/post_install.py
csm/conf/post_upgrade.py
csm/conf/reset.py
csm/conf/setup.py
csm/core/agent/api.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/health.py
csm/core/controllers/routes.py
csm/core/controllers/users.py
csm/core/data/models/users.py
csm/core/services/health.py
csm/core/services/sessions.py
csm/core/services/users.py
csm/plugins/cortx/health.py
schema/feature_endpoint_mapping.json
schema/roles.json
schema/unsupported_features.json
test/csm_user/test_csm_admin_user.py
test/csm_user/test_csm_user.py
test/test_roles.py

Signed-off-by: Shri Metta <shri.metta@seagate.com>
- _GitHub …

Merging latest from main.

---

csm/cli/schema/s3bucketpolicy.json
csm/cli/schema/s3buckets.json

https://jts.seagate.com/browse/EOS-21991
Error occured while creating bucketand bucketpolicy.
Issue was deu to incorrect import path given in cli command json schema
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. …

EOS-21991: s3bucket policy and s3bucket create bugfix

---

csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/audit_log.py
csm/core/services/audit_log.py
csm/plugins/cortx/s3.py

- [EOS-18537](https://jts.seagate.com/browse/EOS-18537)
- Need to expose the API to obtain the S3 audit logs schema, verify that S3 audit logs are returned in JSON format and make the table output in CLI customizable.
- GET /api/v2/auditlogs/schema_info/{component} - reused the API for getting CSM audit logs schema, added {component} part to specify either csm or s3;
- GET /api/v2/auditlogs/show/{component} - will be reused for S3 audit logs completely, no changes are required; sorting and pagination are enabled;
- CLI output is already configured via CLI schema, appropriate columns to be chosen
- _Confirm that Test Cases are added (for both the cases, fix and …

EOS-18537: BE: S3- Audit Log: Update Audit log UI in tabular format

---

csm/conf/post_install.py

https://jts.seagate.com/browse/EOS-21422
Remove Restart=on_failure option from csm_agent.service.
Added conditional addition for service paramters
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/472187760/Guidelines+for+systemd+resource
https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/499417122/Cortx+component+services+control+keys+in+confstore
- _Coding conventions are followed and code is consistent. …

EOS-21422: CSM: Discrepancy in systemd resources.

---

csm/conf/post_install.py
csm/core/controllers/users.py
csm/core/services/users.py

Merge Main to Stable 07-07-2021

---

csm/core/services/audit_log.py
whitesource-components.config

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-21280
- _Describe the problem this patch intends to solve._ Sorting is not enabled on text fields in audit logs
- _Confirm all the …

EOS-21280: Enable Sorting on text fields in ES

---

csm/conf/etc/csm/database.yaml
csm/core/services/audit_log.py
whitesource-components.config

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-21195
- _Describe the problem this patch intends to solve._ ES index is not created error occurs
- _PR is self-reviewed? Yes/No?_ Yes
- …

EOS-21195: Audit log index handling

---

csm/core/blogic/const.py
csm/core/services/audit_log.py
schema/csm_audit_log.json

- [EOS-21280](https://jts.seagate.com/browse/EOS-21280)
- Extract CSM audit log schema to a separate file.
- Update sortable and filterable fields.
-  _Check if the description is clear and explained._ 
-  _Check Acceptance Criterion is defined._
-  _All the tests performed should be mentioned …

EOS-21280: Extract CSM audit log schema to a file

---

csm/core/services/alerts.py

https://jts.seagate.com/browse/EOS-21129
Description for bad alert wasnt able to update. Incorrect description was shown on UI
Flagg added to check to if alert is bad alert.. then update the alert descrition with new one.
- _Confirm Test …

EOS-21129: Stable 206: R2 : Incorrect CPU usage percentage and Incorrect threshold value is reported for the CPU fault alert on CSM.

---

csm/core/controllers/users.py

https://jts.seagate.com/browse/EOS-22642
No public interface for creation of csmadmin user. Authentication added to all csm user creation api.
- _Confirm …

EOS-22642: F-11D: Update create user Rest API to add authentication for all users

---

csm/conf/configure.py
csm/conf/post_install.py
csm/conf/post_upgrade.py

https://jts.seagate.com/browse/EOS-23138
Post-upgrade wasnt calling csm-web config update to add managment ip
-  _Check if the description is clear and explained._ 
-  _Check Acceptance Criterion is defined._
-  _All the tests …

EOS-23138: CSM GUI is not accessible after upgrade

---

csm/cli/schema/auditlog.json
csm/core/agent/api.py
csm/core/blogic/models/audit_log.py
csm/core/services/audit_log.py
schema/csm_audit_log.json
test/test_data/auditlog/auditlog_commands_output.json

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22619
- Payload should be added in CSM audit logs.
1. Get the request params from the URL.
2. If query params are not present, check the content length to check if the request body is present. If request body is present, get it from the request.
3. Insert the this payload in audit logs.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Testing was …

EOS-22619: Added payload in CSM audit logs

---

schema/commands.yaml

Signed-off-by: suryakumar.kumaravelan <suryakumar.kumaravelan@seagate.com>
Feature: https://jts.seagate.com/browse/EOS-20176
*) Added an entry for utils setup.yaml path to commands.yaml as part of utils support bundle script.
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_y
Code change tends to add an entry in commands.yaml so that support bundle framework can track and create support bundle for utils component.
https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_N
- _Coding conventions are followed and code is consistent. Yes/No?_Yes
- _Confirm All CODACY errors are resolved. Yes/No?_Yes
- _Confirm …

EOS-20176: Added utils entry in commands.yaml

---

csm/common/ha_framework.py
csm/common/permission_names.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/cluster_operations.py
csm/core/controllers/routes.py
csm/core/services/cluster_operations.py
csm/plugins/cortx/cluster_operations.py
schema/feature_endpoint_mapping.json
schema/roles.json

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]: Y
- Define Cluster/Node start/stop interfaces and implement stub classes and methods. 
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/576487626/REST+API+Specification+Cluster+Operations
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: Y
- _Coding conventions are followed and code is consistent. Yes/No? Yes
- _Confirm All CODACY errors are resolved. Yes/No? Yes
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? NA
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? NA
- _Confirm Testing was performed with installed RPM. Yes/No? NA
- _Confirm all the ut/regression/smoke test has been …

EOS-22648: Cluster/Node start/stop API design and stub implementation.

---

cicd/cortxcli.spec
csm/conf/post_upgrade.py

* Web config not restored.
* Removed restoring .env file
* Adding update check to post uninstall hook
- _Confirm Testing was performed with installed RPM. …

Rebase F-11DCluster_admin

---

schema/roles.json

- [EOS-23174](https://jts.seagate.com/browse/EOS-23174)
- Monitor user is not able to delete himself.
- Add 'delete' permission to the 'monitor' role,
- Make sure the 'monitor' user is only able to delete himself.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes, tested manually
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ Yes, smoke test
- _PR is self-reviewed? Yes/No?_ Yes
- _GitHub Issue is updated_ No
- _Jira is updated_ Yes
-  _Check if the …

EOS-23174: add 'delete' permission to the 'monitor' role

---

csm/common/timeseries.py

EOS-23026: Spelling mistake in the error message when FROM parameter is greater than TO parameter in GET /api/v2/stats
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_Y
- _Describe the problem this patch intends to solve._ Typo in '/api/v2/stats' end point. …

EOS-23026: Spelling mistake in the error message when FROM parameter is greater than TO parameter in GET /api/v2/stats

---

csm/common/timeseries.py
csm/conf/cleanup.py
csm/conf/reset.py
csm/conf/setup.py

Rebase F-97D-Cleanup-Prefactory

---

csm/cli/schema/cluster_management.json

EOS-22652: Node stop CLI implementation.

---

csm/common/timeseries.py
csm/conf/cleanup.py
csm/conf/reset.py
csm/conf/setup.py
schema/roles.json

Signed-off-by: Alexander Voronov <alexander.voronov@seagate.com>
Co-authored-by: kupranay <66459168+kupranay@users.noreply.github.com>
- _Confirm all the …

Merge Main to Stable 8-09-2021

---

csm/cli/schema/bundle_generate.json

Signed-off-by: Parayya Vastrad <parayya.vastrad@seagate.com>
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ NA
- _Describe the problem this patch intends to solve._ Adding utils component to bundle_generate so are able to generate support bundle for utils component
- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/316735509/Support+Bundle+Framework
- _For Bug describe the fix here._ NA
- _For feature, post the link to the solution page._ NA
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_NA
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ NA
- _Confirm Test Cases …

Added utils component to CSM bundle_generate.json

---

csm/conf/setup.py
csm/core/agent/csm_agent.py
csm/core/services/storage_capacity.py
csm/core/services/users.py
csm/core/services/usl.py
csm/plugins/cortx/provisioner.py
test/csm_user/test_csm_admin_user.py
test/csm_user/test_csm_user.py

- [EOS-23512](https://jts.seagate.com/browse/EOS-23512)
- CSM-agent should be up and running without Provisioner Utils
- Implement lazy initialization for the provisioner plugin
- Review and delete unused provisioner dependencies (UserService, StorageCapacityService, USL)
- Fix flake8 errors and warnings in the provisioner plugin
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm …

EOS-23512: Remove dependency of CSM Agent on provisioner python pacakage

---

csm/conf/setup.py

cluster-admin-creation-issue: Fixed an issue for creating cluster admin user

---

csm/common/runtime.py
csm/core/agent/csm_agent.py

https://jts.seagate.com/browse/EOS-24102
1. Add positional arggument "start" to csm_agent command 
2. Csm_agent should start only when "start" argument is provided.
- _Coding conventions are followed and code is consistent. Yes/No?_y
- _Confirm All CODACY errors are resolved. Yes/No?_y
```
[root@ssc-vm-rhev4-0907 ~]# csm_agent
usage: /usr/bin/csm_agent [-h] {start} [--debug]
where:
start   Start csm_agent
--debug   Enter debug mode
[root@ssc-vm-rhev4-0907 ~]# csm_agent -h
usage: /usr/bin/csm_agent [-h] {start} [--debug]
where:
start   Start csm_agent
--debug   Enter debug mode
[root@ssc-vm-rhev4-0907 ~]# csm_agent  start
CSM agent started with pid 20293
[root@ssc-vm-rhev4-0907 ~]# ======== Running on http://0.0.0.0:28101 ========
(Press CTRL+C to quit)
[root@ssc-vm-rhev4-0907 ~]# ps -ef | …
```

EOS-24102: CORTX K8s: Containerization : Define CSM Agent container entry point

---

.github/workflows/alex_reviewdog.yml
.whitesource
csm/cli/schema/cluster_management.json
csm/cli/schema/support_bundle.json
csm/common/ha/__init__.py
csm/common/ha/cluster_management/__init__.py
csm/common/ha/cluster_management/operations.py
csm/common/ha/cluster_management/operations_factory.py
csm/common/ha_framework.py
csm/common/permission_names.py
csm/common/timeseries.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/cluster_management.py
csm/core/controllers/routes.py
csm/core/services/cluster_management.py
csm/core/services/users.py
csm/plugins/cortx/cluster_management.py
experiments/stats-timelion/requirements.txt
renovate.json
schema/feature_endpoint_mapping.json
schema/roles.json

main to stable merge 20 sept

---

csm/conf/configure.py

Ldap commands replaced with ldap library calls

---

csm/conf/configure.py
csm/core/blogic/const.py
csm/core/services/sessions.py
csm/core/services/users.py

Ldif files Path related changes

---

csm/conf/configure.py

Added olcAccess for authadmin on userPassword attribute

---

csm/conf/configure.py

Minor change in olcAccess for authadmin user

---

csm/core/controllers/users.py

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-24138
- Error message is not clear in user update request when payload is empty.
- Remove python error from the error message
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/cortx …

EOS-24138: Error message is not clear

---

csm/conf/post_install.py
csm/core/agent/csm_agent.py

- Overview: [EOS-24588](https://jts.seagate.com/browse/EOS-24588)
- K8's Logging : Update log_path  [CSM]Test whether the logs are stored in PVC on a given log path
- Read logging destination dir from key cortx>common>storage>log in ConfigStore, example vale : /share/var/log/cortx
Create Component specific dir under that, like /share/var/log/cortx/csm/<machine_id>
- _Confirm that Test Cases are added (for both the cases, fix and feature). …

EOS-24588: K8's Logging -Update log_path [CSM]Test whether the logs are stored in PVC on a given log path

---

csm/core/agent/api.py

[EOS-24116: CSM: CLUSTER Shutdown - Catch SIGTERM, take necessary action and then stop the process.](https://jts.seagate.com/browse/EOS-24116)
- Replace `aiohttp.web.run_app()` to initialize the REST server by a custom static method with similar signature, `_run_server()`.
- `_run_server()` configures the TCP server and sets the signal handlers, before invoking `loop.run_forever()`.
- SIGTERM signal handler sets a flag to indicate that the rest server will shut down, which allows the middleware to return status code 503 onwards.
- SIGTERM signal handler also waits for all previously existing connections to successfuly terminate.
- A new SIGINT signal handler had to be introduced since it was originally set by `aiohttp.web.run_app()`.
- _Coding conventions are …

EOS-24116: CSM: CLUSTER Shutdown - Catch SIGTERM, take necessary action and then stop the process.

---

csm/core/agent/api.py
csm/core/controllers/users.py

Merge Main to stable[8th Oct]

---

csm/conf/post_install.py
csm/core/blogic/const.py

Reverts Seagate/cortx-manager#673

Revert "EOS-24914: SSL certificate: Generate ssl certificate if its not there in the specified path"

---

csm/core/services/users.py
test/user_management/test_api_functional_requirements.py

Rebase kubernetes with main 2nd Nov 2021

---

.github/pull_request_template.md
csm/core/controllers/s3/accounts.py
csm/core/controllers/validators.py
csm/core/data/models/s3.py
csm/core/services/s3/accounts.py
csm/core/services/users.py
csm/plugins/cortx/s3.py
test/user_management/test_api_functional_requirements.py

- Problem statement
-----
[View rendered .github/pull_request_template.md](https://github.com/Seagate/cortx-manager/blob/main/.github/pull_request_template.md)

Merge MAIN to STABLE 02 Nov 2021

---

csm/core/agent/api.py

EOS-25913: Fix : Audit logs interferring with log rotation

---

CODEOWNERS

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
Added Codeowner as per EOS-27261 for cortx-manager

Added Codeowner

---

csm/conf/configure.py

- Deployment failure occurred due to accidental removal of topic creation logic. 

Deployment failure patch

---

csm/conf/configure.py
csm/conf/etc/csm/csm.conf
csm/conf/post_install.py
csm/conf/prepare.py
csm/conf/setup.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/routes.py
csm/core/services/s3/utils.py
csm/core/services/sessions.py

[EOS-28038](https://jts.seagate.com/browse/EOS-28038)
- Addition/removal of keys from CSM configuration based on updated document: [CORTX GConf: Config Store Keys - Public-Cortx - Confluence (atlassian.net)](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/651132980/CORTX+GConf+Config+Store+Keys))
- Add keys in config for access and secret keys.
Add decryption logic for the keys.
These keys will be used for IAM user CRUD operations
Dependency : https://github.com/Seagate/cortx-prvsnr/pull/6326/
- Added updated keys in csm configuration(refer [EOS-28038](https://jts.seagate.com/browse/EOS-28038) )
-  Removed deprecated keys with related code. …

EOS-28038: Fetch access and secret keys for root IAM user

---

csm/core/controllers/cluster_management.py

- Jira: [EOS-27837](https://jts.seagate.com/browse/EOS-27837)
- Not getting expected responses for shutdown REST API for negative scenarios.
- Fix : Add validation check such that api should not accept unsupported operations.
Build used : [cortx-all-image-custom-ci/2084/](http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/2084/)
1. Positive scenario:
2. Negative scenario: invalid operation 
3. Negative scenario: empty operation

EOS-27837:(F-8B)-Not getting expected responses for REST API for negative scenarios.

---

csm/common/permission_names.py
csm/conf/configure.py
csm/conf/etc/csm/csm.conf
csm/conf/post_install.py
csm/conf/prepare.py
csm/conf/setup.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/__init__.py
csm/core/controllers/rgw/s3/__init__.py
csm/core/controllers/rgw/s3/base.py
csm/core/controllers/rgw/s3/users.py
csm/core/controllers/routes.py
csm/core/controllers/users.py
csm/core/data/models/rgw.py
csm/core/services/rgw/s3/__init__.py
csm/core/services/rgw/s3/users.py
csm/core/services/rgw/s3/utils.py
csm/core/services/s3/utils.py
csm/core/services/sessions.py
csm/plugins/cortx/rgw.py
schema/feature_endpoint_mapping.json
schema/rgw_admin_api_operations.json
schema/roles.json

- [EOS-28041: CSM REST API to get IAM User](https://jts.seagate.com/browse/EOS-28041)
- [EOS-28043: CSM REST API to remove IAM User](https://jts.seagate.com/browse/EOS-28043)
[Get User Info REST API Specs](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/899121830/GET+IAM+user%3A+REST+API+Specifications)
[Delete IAM User REST API Specs](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/899121843/Delete+IAM+user%3A+REST+API+Specifications?src=jira)
**1. Create one IAM user - demouser1**
**2. Get "demouser1" using csm rest api**
**3. Delete the same user - "demouser1"**
- …

F45i:  Create IAM user

---

csm/core/blogic/const.py
csm/core/controllers/rgw/s3/users.py
csm/core/data/models/rgw.py
csm/core/services/rgw/s3/users.py
csm/core/services/rgw/s3/utils.py
csm/plugins/cortx/rgw.py
schema/rgw_admin_api_operations.json

- [CORTX-28042: REST API to Modify IAM User information](https://jts.seagate.com/browse/CORTX-28042)
-  [API Specifications](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/917569938/Modify+IAM+user+REST+API+Specifications)
**1. Create a IAM user**
**2. Fetch the same user**
**3. Modify the user**
**4. Error response in case of connection to S3 failed**
**5. Error response in case of request to S3 timed out**

CORTX-28042: [RGW] REST API to modify IAM user

---

csm/core/controllers/routes.py
csm/core/controllers/storage_capacity.py

- [CORTX-29454- Unsupported Capacity API](https://jts.seagate.com/browse/CORTX-29454)
-  Commented View endpoint for unsupported capacity api
- Added supported view endpoints in routes
- [Custom Build jenkins Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/5660/)
- Custom Build
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5660-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5660-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5660-custom-ci
- [Deployment job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/2083/)
- VM deployed
- Unsupported Endpoint (/api/v2/capacity)
- Supported Endpoint …

CORTX-29454:  Unsupported Capacity API

---

csm/conf/configure.py
csm/conf/csm_default.conf
csm/conf/etc/csm/csm.conf
csm/core/blogic/const.py
csm/core/controllers/cluster_management.py
csm/core/services/cluster_management.py
csm/plugins/cortx/cluster_management.py
schema/ha_api_operations.json

- [CORTX-30315 JIRA Ticket](https://jts.seagate.com/browse/CORTX-30315)
-  Supported Confluence Specification:-
[HA REST APIs - Private-Cortx - Confluence (atlassian.net)](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/981434369/HA+REST+APIs)
[Node failure API specifications - Private-Cortx - Confluence (atlassian.net)](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/983400463/Node+failure+API+specifications)
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/5941/)
- Custom Build Image
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5941-custom-ci …

CORTX-30315: Get Node status

---

csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/controllers/routes.py
csm/core/controllers/storage_capacity.py
csm/core/services/storage_capacity.py
schema/rgw_admin_api_operations.json

- [CORTX-30285 JIRA Ticket](https://jts.seagate.com/browse/CORTX-30285)
-  [REST API Specification](https://seagate-systems.atlassian.net/l/c/ms1J10fi)
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/5908/)
- Custom Build Image
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5908-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5908-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5908-custom-ci
- [Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/3353/)
- Cluster deployed in one node setup …

CORTX-30285: User level Capacity usage for Admin

---

.github/pull_request_template.md
CORTXManagerQuickstartGuide.md

- [CORTX-30825](https://jts.seagate.com/browse/CORTX-30825)
-----
[View rendered CORTXManagerQuickstartGuide.md](https://github.com/Seagate/cortx-manager/blob/CORTX-30825-codacy-fixes-ap_new/CORTXManagerQuickstartGuide.md)

Cortx-30825: Markdown file codacy fixes

---

.github/workflows/alex_reviewdog.yml

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Fix for Alex scan issue where below error was being reported in reviewdog as,
`reviewdog: PullRequest needs 'git' command: failed to run 'git rev-parse --show-prefix': exit status 128`

CORTX-30785: Fix for Alex scan issue

---

csm/core/data/models/session.py
csm/core/services/session/session_factory.py

- Jira link:  [CORTX-31079](https://jts.seagate.com/browse/CORTX-31079)
- Send shutdown signal fails, rest api returning error code 4101
- Bug introduced due to change in session management related code.
- Changes in session management were required from csm side.
- Custom Build details:
Test case1A:  Admin user is able to send shutdown signal:
Test case1B: Monitor user must not able to send shutdown signal:
" src="https://user-images.githubusercontent.com/68841079/166614198-23d33e04-83f3-479d-ae40-0ffce8b098fc.PNG">
Test case 2: Session management
1.  Use default admin user to create admin user   
2. Stop using default admin …

CORTX-31079: Send shutdown signal fails, rest api returning error code 4104

---

csm/core/controllers/rgw/s3/users.py
csm/core/controllers/users.py

- [CORTX-31170 JIRA ticket](https://jts.seagate.com/browse/CORTX-31170)
-  [Management API Changes](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1006305559/Management+API+Changes)
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6117)
- Custom Build Images
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-6117-custom-ci 
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6117-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6117-custom-ci
- [Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cl …

CORTX-31170: CSM user management and IAM users management API changes

---

templates/swagger-ui/swagger.json

- Swagger Docs: Publish CSM API docs on /v2/api/docs
-  [Jira : CORTX-31160](https://jts.seagate.com/browse/CORTX-31160)

CORTX-31160:Swagger Docs: Publish CSM API docs on /v2/api/docs

---

csm/core/controllers/rgw/s3/users.py

- [Expose an API to fetch listing of all the IAM users](https://jts.seagate.com/browse/CORTX-31186)
- RGW specs- https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/1014693994/User+List+API+Specification
- CSM Specs- https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1015087186/List+IAM+Users
1. Range validation applied on max_entries field
2. Happy Path

CORTX-31186: Validation added for fields of list IAM users API

---

csm/cli/cortxcli.py
csm/common/utility.py
csm/core/blogic/const.py
csm/core/controllers/rgw/s3/base.py
csm/core/controllers/rgw/s3/bucket.py
csm/core/controllers/rgw/s3/users.py
csm/plugins/cortx/rgw.py
schema/suppress_payload.json
test/test_framework/csm_test.py

-   \[ \] Jira and state/status is updated and JIRA is updated with PR link
-   \[ \] Check if the description is clear and …

CORTX-31454: Suppress SK from GET IAM user info and restrictions on internal IAM user [feature to main]

---

csm/core/services/storage_capacity.py

-   \[ \] Jira and state/status is updated and JIRA …

EOS-30799: Disabling SSL certificate verification

---

csm/core/data/models/rgw.py
csm/core/services/rgw/s3/utils.py
csm/plugins/cortx/rgw.py

-   [CORTX-31950](https://jts.seagate.com/browse/CORTX-31950): CSM-S3 communication should be on https.
-   Select HTTPS endpoint from the list of mini-provisioned endpoints.
-   Pass URL as it is to the S3 cilent.
- NOTE: This PR depends on https://github.com/Seagate/cortx-utils/pull/824. Please, merge cortx-utils fix first.
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6649/)
- Custom Build for deployment
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6649-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6649-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6649-custom-ci
- [Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cl …

CORTX-31950: connect to RGW via HTTPS

---

csm/conf/configure.py

-   \[ \] Jira and state/status is updated and JIRA …

CORTX-31536: Handled MessageBus Error in config phase

---

templates/swagger-ui/swagger.json

-   [CORTX-32263](https://jts.seagate.com/browse/CORTX-32263)
-   [REST API documentation](https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/994836509/CORTX+Management+Endpoints)
- [Custom Build Job](https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6902)
- [Deployment Job](https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/7753/)
- Custom Build 
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-6902-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6902-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-control:2.0.0-6902 -custom-ci
-   \[ \] Coding conventions are followed and code is …

CORTX-32263: Update Swagger

---

csm/core/agent/api.py

-   [CORTX-33700](https://jts.seagate.com/browse/CORTX-33700)
-  Handle exception at Throttle level 
-   \[ \] Jira and state/status is updated and JIRA is updated …

CORTX-33700: Handled exception in throttler middleware and added comments

---

csm/core/agent/api.py

-   [CORTX-33764](https://jts.seagate.com/browse/CORTX-33764)
-   Set resource limit to calculation formulae
-   \[ \] Jira and state/status is updated and JIRA is …

Resource Limit is set to calculations

---

csm/conf/setup.py
csm/core/agent/api.py
csm/core/agent/csm_agent.py
csm/core/controllers/login.py
csm/core/controllers/rgw/s3/users.py
csm/core/controllers/users.py
csm/core/services/rgw/s3/users.py
csm/core/services/sessions.py
csm/plugins/cortx/rgw.py

-   [CORTX-32719:Improve CSM service logs to include IEM and error details](https://jts.seagate.com/browse/CORTX-32719)
-   \[x] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[x] PR is self reviewed
-   \[x] Jira and state/status is …

CORTX-32719: Improve CSM service logs and error details

---

csm/core/blogic/const.py
csm/core/services/storage_capacity.py
csm/plugins/cortx/rgw.py

Jira story: [CORTX-32262](https://jts.seagate.com/browse/CORTX-32262)
-   Request timeout to be 20 seconds
-  Unable to connect / Server unreachable we need to add retries
1. S3 Server
2. Hare
- Build details:
- Happy path s3 services:
- Service unavailable
- Happy path cluster status api
- Service unavailable
-   \[ \] Interface change (if any) are …

CORTX-32262:CSM Connection handling

---

csm/conf/setup.py
csm/core/agent/csm_agent.py
csm/core/blogic/const.py
csm/core/services/session/session_factory.py
csm/core/services/users.py

-   \[ \] Jira and state/status is updated and JIRA is updated with …

CORTX-33949:CSM consul Connection handling
